In [1]:
from astropy import units as u
from astropy.time import Time, TimeDelta
from astropy.coordinates import solar_system_ephemeris
solar_system_ephemeris.set("jpl")
from poliastro.bodies import Sun, Earth, Moon
from poliastro.ephem import Ephem
from poliastro.util import time_range
import matplotlib.pyplot as plt
import datetime
import random
from poliastro.twobody import Orbit
from poliastro.maneuver import Maneuver
import math
from poliastro.plotting import OrbitPlotter3D
from astropy.utils.data import conf
import numpy as np

In [2]:
#Finds date where body is a distance d away
def find_date(d):
    low = 0 
    high = mission_length
    mid = 0
    
    while low <= high:
        mid = (high + low) / 2
        sc_pos = np.array([ss_trans.propagate(date_launch + TimeDelta(mid * u.day)).sample()[0].xyz])
        body_pos = np.array([ss_target.propagate(date_launch + TimeDelta(mid * u.day)).sample()[0].xyz])
        pos = sc_pos - body_pos
        dist = int(np.linalg.norm(pos))
        
        #print(date_launch + TimeDelta(mid * u.day))
        if dist > d:
            low = mid
        elif dist < d:
            high = mid
        else:
            #print(dist)
            print(date_launch + TimeDelta(mid * u.day))
            return (date_launch + TimeDelta(mid * u.day))

In [3]:
#Gives dx where 100 * dx = end - start
def find_dx(start, end):
    return float(str((end - start)/ 100))

In [4]:
#Filters and saves 100 data points between min_distance and max_distance
def filtered_positions(min_distance, max_distance):
    start_date = find_date(max_distance)
    end_date = find_date(min_distance)
    dx = find_dx(start_date, end_date)
    print(start_date)
    print(end_date)
    #print(dx)
    i = 0
    f_sc_launch_pos = np.array([ss_trans.propagate(start_date + TimeDelta(i * dx * u.day)).sample()[0].xyz])
    f_body_launch_pos = np.array([ss_target.propagate(start_date + TimeDelta(i * dx * u.day)).sample()[0].xyz])
    f_cur_pos = f_sc_launch_pos - f_body_launch_pos
    filtered_pos = f_cur_pos
    #print(np.linalg.norm(f_cur_pos))
    i += 1
    
    while(i < 100):
        f_cur_pos_sc = np.array([ss_trans.propagate(start_date + TimeDelta(i * dx * u.day)).sample()[0].xyz])
        f_cur_pos_body = np.array([ss_target.propagate(start_date + TimeDelta(i * dx * u.day)).sample()[0].xyz])
        filtered_pos = np.append(filtered_pos, f_cur_pos_sc - f_cur_pos_body, axis = 0)
        #print(np.linalg.norm(f_cur_pos_sc - f_cur_pos_body))
        i += 1
    #print("filtered complete")
    print(filtered_pos)
    return filtered_pos
    
    #print(filtered_pos)

In [5]:
def R_2vect(vector_orig, vector_fin):
    R = np.zeros((3,3))
    # Convert the vectors to unit vectors.
    vector_orig = vector_orig / np.linalg.norm(vector_orig)
    vector_fin = vector_fin / np.linalg.norm(vector_fin)
    # The rotation axis (normalised).
    axis = np.cross(vector_orig, vector_fin)
    axis_len = np.linalg.norm(axis)
    if axis_len != 0.0:
        axis = axis / axis_len
    # Alias the axis coordinates.
    x = axis[0]
    y = axis[1]
    z = axis[2]
    # The rotation angle.
    angle = math.acos(np.dot(vector_orig, vector_fin))
    # Trig functions (only need to do this maths once!).
    ca = math.cos(angle)
    sa = math.sin(angle)
    # Calculate the rotation matrix elements.
    R[0,0] = 1.0 + (1.0 - ca)*(x**2 - 1.0)
    R[0,1] = -z*sa + (1.0 - ca)*x*y
    R[0,2] = y*sa + (1.0 - ca)*x*z
    R[1,0] = z*sa+(1.0 - ca)*x*y
    R[1,1] = 1.0 + (1.0 - ca)*(y**2 - 1.0)
    R[1,2] = -x*sa+(1.0 - ca)*y*z
    R[2,0] = -y*sa+(1.0 - ca)*x*z
    R[2,1] = x*sa+(1.0 - ca)*y*z
    R[2,2] = 1.0 + (1.0 - ca)*(z**2 - 1.0)
    return R
def rotationMatrixToEulerAngles(R) :
    #assert(isRotationMatrix(R))
    sy = math.sqrt(R[0,0] * R[0,0] +  R[1,0] * R[1,0])
    singular = sy < 1e-6
    if  not singular :
        x = math.atan2(R[2,1] , R[2,2])
        y = math.atan2(-R[2,0], sy)
        z = math.atan2(R[1,0], R[0,0])
    else :
        x = math.atan2(-R[1,2], R[1,1])
        y = math.atan2(-R[2,0], sy)
        z = 0
    return np.array([x, y, z])

def calculateEuler(path):
    orbits_attitudes = None
    vector_orig = [0,0,1]
    vec_orig_flip = -1*np.array(vector_orig)
    pos = np.load(path + '.npy')
    for k in range(len(pos)):
    # pos_ is the position vector from the target body to the camera (pos_ = camera_position - target_body_position)
        for i in range(100):
            pos_ = -1*pos[k][i]
            R = R_2vect(vec_orig_flip, pos_) 
            angle0_blend = rotationMatrixToEulerAngles(R)
            if i == 0:
                euler_pos_xyz = np.array([angle0_blend])
            else:
                euler_pos_xyz = np.append(euler_pos_xyz, [angle0_blend], axis = 0)
    #print(euler_pos_xyz)
        if orbits_attitudes is None:
            orbits_attitudes = np.array([euler_pos_xyz])
        else:
            orbits_attitudes = np.append(orbits_attitudes, [euler_pos_xyz], axis = 0)
        np.save('orbits_attitudes', orbits_attitudes)

#calculateEuler('pos_xyz')


In [6]:
random.seed("SSDS")
dates = []
asteroid_choice = []
orbits_positions = None

In [7]:
for i in range(0,175):
    chosen_body = random.randint(0,3)
    asteroid_choice.append(chosen_body)
    if chosen_body == 0:
        chosen_body = "Bennu"
    elif chosen_body == 1:
        chosen_body = "Itokawa"
    elif chosen_body == 2:
        chosen_body = "Mithra"
    elif chosen_body == 3:
        chosen_body = "Toutatis"
    
    #Launch Date
    launch_year = random.randint(2000,2019)
    launch_month = random.randint(1,12)
    launch_day = random.randint(1,28)

    #Arrival Date
    arrival_year = random.randint(launch_year+1, launch_year + 5)
    arrival_month = random.randint(launch_month,12)
    arrival_day = random.randint(launch_day, 28)
    
    #Converting to dates
    l_dt = datetime.date(launch_year, launch_month, launch_day)
    a_dt = datetime.date(arrival_year, arrival_month, arrival_day)
    mission_length = (a_dt - l_dt).days
    
    #print(a_dt > l_dt)
    #print(chosen_body)

    launch_date_string = str(launch_year) + "-" + str(launch_month) + "-" + str(launch_day)
    arrival_date_string = str(arrival_year) + "-" + str(arrival_month) + "-" + str(arrival_day)
    
    dates.append(launch_date_string + " " + arrival_date_string)
    #print(launch_date_string + " " + arrival_date_string)
    #print(datetime.datetime.now())
    date_launch = Time(launch_date_string, scale="tdb")
    date_arrival = Time(arrival_date_string, scale="tdb")
    points = 100

    #Filters
    min_distance = 50000
    max_distance = 500000
    
    #Ephemerides for Body and Earth
    body = Ephem.from_horizons(chosen_body, time_range(date_launch, end=date_arrival, periods=points), attractor=Sun)
    earth = Ephem.from_body(Earth, time_range(date_launch, end=date_arrival, periods=points))

    #Orbits for Body and Earth
    ss_body = Orbit.from_ephem(Sun, body, date_arrival)
    ss_earth = Orbit.from_ephem(Sun, earth, date_launch)
    
    

    #Lambert maneuver between from Earth to Body
    man_lambert = Maneuver.lambert(ss_earth, ss_body, short=False)

    #Orbits of spacecraft and Body
    ss_trans, ss_target = ss_earth.apply_maneuver(man_lambert, intermediate=True)
    
    sc_launch_pos = np.array([ss_trans.propagate(date_launch).sample()[0].xyz])
    body_launch_pos = np.array([ss_target.propagate(date_launch).sample()[0].xyz])

    sc_arrival_pos = np.array([ss_trans.propagate(date_arrival).sample()[0].xyz])
    body_arrival_pos = np.array([ss_target.propagate(date_arrival).sample()[0].xyz])

    days = 1
    cur_pos = sc_launch_pos - body_launch_pos
    pos = cur_pos

    #print("orbits calculated")
    '''
    while(days <= mission_length):
        cur_pos_sc = np.array([ss_trans.propagate(date_launch + TimeDelta(days * u.day)).sample()[0].xyz])
        cur_pos_body = np.array([ss_target.propagate(date_launch + TimeDelta(days * u.day)).sample()[0].xyz])
        pos = np.append(pos, cur_pos_sc - cur_pos_body, axis = 0)
        days += 1
    '''
    #print("filtered")
    filtered_pos = filtered_positions(min_distance, max_distance)
    #print(np.shape(filtered_pos))
    #print(np.shape(orbits_positions))
    if orbits_positions is None:
        orbits_positions = np.array([filtered_pos])
    else:
        orbits_positions = np.append(orbits_positions, [filtered_pos], axis = 0)
    #np.save('pos_xyz', pos)
    #np.save('filtered_pos_xyz', filtered_pos)
    print(i)
#print(orbits_positions)
np.save('orbits_positions', orbits_positions)
np.save('asteroid_choice', asteroid_choice)
calculateEuler('orbits_positions')

C:\Users\srika\anaconda3\lib\site-packages\astroquery\jplhorizons\core.py:1048: UserWarning: The uri used in this query is very long and might have been truncated. The results of the query might be compromised. If you queried a list of epochs, consider querying a range.
  warnings.warn(('The uri used in this query is very long '


2003-11-18 20:07:59.878
2003-11-18 23:36:47.962
2003-11-18 20:07:59.878
2003-11-18 23:36:47.962
[[ 379766.41697446 -298123.1780549  -130002.62655348]
 [ 376348.50894064 -295440.06051517 -128832.59738162]
 [ 372930.60137376 -292756.94336832 -127662.56842531]
 [ 369512.69426985 -290073.82660879 -126492.53968184]
 [ 366094.7876247  -287390.71023329 -125322.51114931]
 [ 362676.88143405 -284707.59423687 -124152.48282529]
 [ 359258.97569372 -282024.47861709 -122982.45470823]
 [ 355841.07039918 -279341.36337247 -121812.42679697]
 [ 352423.16554661 -276658.24849713 -120642.39908864]
 [ 349005.26113158 -273975.1339879  -119472.37158149]
 [ 345587.35715032 -271292.01983993 -118302.34427308]
 [ 342169.45359817 -268608.9060511  -117132.31716194]
 [ 338751.55047084 -265925.79261877 -115962.29024653]
 [ 335333.64776401 -263242.67953828 -114792.26352444]
 [ 331915.74547364 -260559.56680639 -113622.23699385]
 [ 328497.84359561 -257876.45441779 -112452.21065213]
 [ 325079.94212554 -255193.34237053 -111

C:\Users\srika\anaconda3\lib\site-packages\astroquery\jplhorizons\core.py:1048: UserWarning: The uri used in this query is very long and might have been truncated. The results of the query might be compromised. If you queried a list of epochs, consider querying a range.
  warnings.warn(('The uri used in this query is very long '


2011-10-27 18:30:42.407
2011-10-27 23:27:04.212
2011-10-27 18:30:42.407
2011-10-27 23:27:04.212
[[226328.70729291 445580.57644999 -15288.37656485]
 [224291.71514978 441570.32973379 -15150.81340878]
 [222254.72400902 437560.08377162 -15013.24938624]
 [220217.73386721 433549.83855741 -14875.68450662]
 [218180.74471024 429539.59408391 -14738.11877634]
 [216143.75652926 425529.35034415 -14600.55220328]
 [214106.76931685 421519.10733174 -14462.98479568]
 [212069.78306325 417508.86503983 -14325.41656109]
 [210032.79775858 413498.62346153 -14187.84750719]
 [207995.81339473 409488.38259006 -14050.277642  ]
 [205958.82996012 405478.14241847 -13912.70697261]
 [203921.84745166 401467.90294075 -13775.13550849]
 [201884.86585417 397457.66414934 -13637.5632558 ]
 [199847.88516054 393447.4260377  -13499.99022281]
 [197810.90535928 389437.18859877 -13362.41641675]
 [195773.92644824 385426.95182659 -13224.84184733]
 [193736.94840924 381416.7157134  -13087.26651978]
 [191699.97124156 377406.48025322 -12

2018-08-20 07:58:38.920
2018-08-22 17:35:51.676
2018-08-20 07:58:38.920
2018-08-22 17:35:51.676
[[358040.49244179 244149.39839661 249397.23318592]
 [354818.14019437 241951.94886923 247152.63354525]
 [351595.78771293 239754.50224984 244908.03463373]
 [348373.4349983  237557.05851167 242663.4364447 ]
 [345151.08205338 235359.61762792 240418.83897138]
 [341928.72888023 233162.17957348 238174.24220717]
 [338706.37547988 230964.74432117 235929.64614582]
 [335484.02185571 228767.31184494 233685.05078048]
 [332261.66800788 226569.88211709 231440.45610398]
 [329039.31393944 224372.45511329 229195.8621107 ]
 [325816.95965257 222175.03080648 226951.26879367]
 [322594.60514894 219977.60916895 224706.67614567]
 [319372.25042932 217780.19017512 222462.08416045]
 [316149.89549792 215582.7737999  220217.49283174]
 [312927.54035529 213385.36001468 217972.90215257]
 [309705.18500383 211187.94879496 215728.31211653]
 [306482.82944547 208990.54011303 213483.72271666]
 [303260.47368212 206793.13394362 211

2012-08-08 18:16:46.395
2012-08-09 21:01:40.511
2012-08-08 18:16:46.395
2012-08-09 21:01:40.511
[[104186.0573532  421326.73394096 248253.50900286]
 [103248.39067027 417534.76255739 246019.21689326]
 [102310.72381043 413742.79214525 243784.9251498 ]
 [101373.05677465 409950.82269424 241550.63376862]
 [100435.38956419 406158.85419607 239316.34274647]
 [ 99497.72218084 402366.8866415  237082.05207968]
 [ 98560.05462694 398574.92002308 234847.76176608]
 [ 97622.38690251 394782.9543308  232613.47180125]
 [ 96684.71901092 390990.98955685 230379.18218264]
 [ 95747.05095223 387199.02569163 228144.89290658]
 [ 94809.38272929 383407.06272674 225910.60396975]
 [ 93871.71434221 379615.10065311 223676.3153688 ]
 [ 92934.04579362 375823.13946164 221442.02710032]
 [ 91996.3770853  372031.17914504 219207.7391617 ]
 [ 91058.70821792 368239.21969265 216973.45154843]
 [ 90121.03919417 364447.26109809 214739.16425881]
 [ 89183.37001473 360655.30334985 212504.87728792]
 [ 88245.7006813  356863.34644115 210

2006-08-25 12:49:43.615
2006-08-25 22:52:58.332
2006-08-25 12:49:43.615
2006-08-25 22:52:58.332
[[437658.18981779 223722.51547885  91674.5141812 ]
 [433719.26734769 221709.01277614  90849.44350675]
 [429780.34493089 219695.51011831  90024.37285125]
 [425841.42256719 217682.00750786  89199.3022157 ]
 [421902.50025696 215668.50494254  88374.23159918]
 [417963.57799917 213655.0024218   87549.16100129]
 [414024.65579212 211641.49994588  86724.09042263]
 [410085.73363864 209627.99751592  85899.01986325]
 [406146.81153387 207614.4951272   85073.94932124]
 [402207.88948029 205600.99278325  84248.87879825]
 [398268.9674769  203587.49048257  83423.80829334]
 [394330.04552311 201573.98822391  82598.7378062 ]
 [390391.12361896 199560.48600894  81773.66733769]
 [386452.20176214 197546.98383498  80948.5968861 ]
 [382513.27995241 195533.48170108  80123.52645165]
 [378574.35819262 193519.97961038  79298.45603547]
 [374635.43647701 191506.4775579   78473.38563541]
 [370696.51481026 189492.97554737  77

2010-10-13 13:24:50.750
2010-10-13 22:56:29.026
2010-10-13 13:24:50.750
2010-10-13 22:56:29.026
[[394993.16521394 284316.63793564 114653.25718585]
 [391438.22997397 281757.79030812 113621.37868756]
 [387883.2947821  279198.9427219  112589.5002068 ]
 [384328.35963929 276640.09517777 111557.62174392]
 [380773.42454487 274081.24767256 110525.74329785]
 [377218.48949605 271522.40020788 109493.86486885]
 [373663.55449462 268963.55278182 108461.98645672]
 [370108.61954051 266404.7053954  107430.10806119]
 [366553.68463242 263845.85804862 106398.22968286]
 [362998.74977028 261287.01074058 105366.35132095]
 [359443.81495267 258728.16347015 104334.47297505]
 [355888.88018066 256169.31623697 103302.59464517]
 [352333.94545323 253610.46904314 102270.71633196]
 [348779.01076752 251051.62188393 101238.83803374]
 [345224.07612723 248492.77476317 100206.95975178]
 [341669.14152837 245933.92767727  99175.08148453]
 [338114.20697451 243375.08062899  98143.20323348]
 [334559.27246016 240816.23361421  97

2014-10-24 06:18:17.107
2014-10-24 22:13:49.518
2014-10-24 06:18:17.107
2014-10-24 22:13:49.518
[[-485735.14215082   30750.52610587  114528.28070364]
 [-481363.3750214    30473.59388947  113497.46904744]
 [-476991.61234826   30196.66650988  112466.65903542]
 [-472619.85409299   29919.74392197  111435.85065202]
 [-468248.10021564   29642.82608271  110405.04388259]
 [-463876.35067734   29365.91294786  109374.2387121 ]
 [-459504.60543859   29089.00447373  108343.43512563]
 [-455132.86446011   28812.10061681  107312.63310835]
 [-450761.12770268   28535.20133282  106281.83264519]
 [-446389.39512646   28258.30657785  105251.03372121]
 [-442017.66669264   27981.41630872  104220.23632168]
 [-437645.94236162   27704.53048095  103189.44043135]
 [-433274.22209397   27427.64905107  102158.64603561]
 [-428902.50584996   27150.77197534  101127.85311936]
 [-424530.79359025   26873.89920917  100097.0616675 ]
 [-420159.08527571   26597.03071006   99066.27166562]
 [-415787.38086626   26320.16643275   98

2007-08-26 19:38:30.081
2007-08-26 23:33:50.998
2007-08-26 19:38:30.081
2007-08-26 23:33:50.998
[[ -47654.45913397 -431389.40245697 -248259.64925261]
 [ -47225.56265733 -427506.89285049 -246025.30970427]
 [ -46796.66635877 -423624.38344994 -243790.97026996]
 [ -46367.77024099 -419741.87425789 -241556.63095124]
 [ -45938.87429801 -415859.36526862 -239322.29174496]
 [ -45509.97853111 -411976.85648379 -237087.95265192]
 [ -45081.08293788 -408094.3478981  -234853.61366932]
 [ -44652.18751736 -404211.83951235 -232619.27479748]
 [ -44223.2922653  -400329.3313224  -230384.9360342 ]
 [ -43794.39718436 -396446.82332942 -228150.59738013]
 [ -43365.50226974 -392564.31552911 -225916.25883284]
 [ -42936.6075201  -388681.80792019 -223681.92039147]
 [ -42507.71293409 -384799.30050036 -221447.58205511]
 [ -42078.81851014 -380916.79326692 -219213.24382189]
 [ -41649.92424729 -377034.28622118 -216978.90569273]
 [ -41221.03014313 -373151.77935842 -214744.56766517]
 [ -40792.13619651 -369269.27267769 -212

2018-12-12 19:30:00.575
2018-12-12 23:33:00.058
2018-12-12 19:30:00.575
2018-12-12 23:33:00.058
[[-65960.72524559 451372.88678586 204725.13039745]
 [-65367.08265971 447310.52694434 202882.60262847]
 [-64773.4399433  443248.16725287 201040.07492241]
 [-64179.79713993 439185.80762938 199197.54724365]
 [-63586.15422568 435123.44811863 197355.01961185]
 [-62992.51122083 431061.08868435 195512.49201122]
 [-62398.86809438 426998.72938758 193669.96446788]
 [-61805.22486912 422936.37018362 191827.43696289]
 [-61211.58155362 418874.01105809 189984.90948997]
 [-60617.93812482 414811.65205631 188142.3820686 ]
 [-60024.29461518 410749.29311621 186299.854672  ]
 [-59430.65099037 406686.93430564 184457.32732978]
 [-58837.00726889 402624.57558775 182614.8000256 ]
 [-58243.36346972 398562.21692944 180772.27274553]
 [-57649.71955921 394499.85839558 178929.74551751]
 [-57056.07556319 390437.49993631 177087.21831973]
 [-56462.43146512 386375.14158612 175244.6911675 ]
 [-55868.78728041 382312.78331554 173

2021-05-14 19:27:07.809
2021-05-14 23:32:42.754
2021-05-14 19:27:07.809
2021-05-14 23:32:42.754
[[ 88434.88714036 133414.54988645 473687.72926321]
 [ 87638.95106637 132213.80208459 469424.55338416]
 [ 86843.01563069 131013.05479701 465161.37734246]
 [ 86047.08082686 129812.30801927 460898.20113933]
 [ 85251.14665003 128611.56174658 456635.0247768 ]
 [ 84455.21309252 127410.81597483 452371.84825522]
 [ 83659.2801508  126210.07069841 448108.67157735]
 [ 82863.34781806 125009.32591355 443845.49474422]
 [ 82067.41608787 123808.58161542 439582.31775674]
 [ 81271.48495542 122607.83779918 435319.14061709]
 [ 80475.55441475 121407.09446031 431055.96332654]
 [ 79679.6244593  120206.35159437 426792.78588614]
 [ 78883.69508363 119005.60919662 422529.60829768]
 [ 78087.76628235 117804.86726241 418266.43056276]
 [ 77291.83804987 116604.12578687 414003.25268291]
 [ 76495.91038017 115403.38476562 409740.07465964]
 [ 75699.98326673 114202.64419414 405476.8964939 ]
 [ 74904.0567041  113001.90406764 401

2011-09-18 06:40:06.006
2011-09-24 07:52:44.502
2011-09-18 06:40:06.006
2011-09-24 07:52:44.502
[[418787.23184402  83218.92191055 260177.52979377]
 [415020.13130189  82477.02035528 257843.33009004]
 [411252.95768814  81734.93430814 255508.93069143]
 [407485.71203284  80992.66511595 253174.33318193]
 [403718.39536023  80250.21413191 250839.53914993]
 [399951.00868842  79507.58271506 248504.55018772]
 [396183.55303019  78764.77223088 246169.36789208]
 [392416.0293933   78021.78405099 243833.9938639 ]
 [388648.43877804  77278.61955249 241498.42970801]
 [384880.78218023  76535.2801192  239162.67703362]
 [381113.06058887  75791.76714066 236826.73745409]
 [377345.27498755  75048.08201186 234490.61258664]
 [373577.42635441  74304.22613558 232154.3040534 ]
 [369809.51566079  73560.2009196  229817.81348015]
 [366041.54387295  72816.00777781 227481.142497  ]
 [362273.51194996  72071.64813    225144.29273809]
 [358505.42084607  71327.12340261 222807.26584202]
 [354737.27150875  70582.43502788 220

2011-04-25 15:04:04.939
2011-04-25 23:06:24.463
2011-04-25 15:04:04.939
2011-04-25 23:06:24.463
[[300213.57472675 360636.37196076 172667.9210266 ]
 [297511.64569989 357390.62667036 171113.90266091]
 [294809.71693741 354144.88195947 169559.88453159]
 [292107.78843649 350899.13782349 168005.8666368 ]
 [289405.86019529 347653.39425656 166451.8489743 ]
 [286703.93221325 344407.65125412 164897.83154197]
 [284002.0044829  341161.90880999 163343.81433752]
 [281300.07700747 337916.16691995 161789.79735918]
 [278598.14978203 334670.42557815 160235.78060451]
 [275896.22280262 331424.68477941 158681.76407138]
 [273194.29606834 328178.94451857 157127.7477577 ]
 [270492.36957711 324933.2047905  155573.7316615 ]
 [267790.44332606 321687.46558946 154019.71578027]
 [265088.51731272 318441.72691071 152465.70011209]
 [262386.59153453 315195.9887487  150911.68465491]
 [259684.66599149 311950.25109881 149357.66940658]
 [256982.74067876 308704.51395521 147803.65436484]
 [254280.81559142 305458.77731225 146

2013-04-17 20:28:08.470
2013-04-17 23:38:48.831
2013-04-17 20:28:08.470
2013-04-17 23:38:48.831
[[-497251.82414174   46652.26927996   23753.27273895]
 [-492776.5619697    46232.39835061   23539.49310153]
 [-488301.29985058   45812.5274522    23325.7134777 ]
 [-483826.03777564   45392.65658055   23111.93386562]
 [-479350.77575451   44972.78573897   22898.15426682]
 [-474875.51377857   44552.91492489   22684.3746801 ]
 [-470400.2518487    44133.04413924   22470.5951058 ]
 [-465924.98996985   43713.17338184   22256.81554399]
 [-461449.72813779   43293.30265211   22043.03599429]
 [-456974.46634966   42873.4319489    21829.25645628]
 [-452499.20460838   42453.56127296   21615.47693031]
 [-448023.94291312   42033.69062418   21401.69741622]
 [-443548.68126446   41613.82000227   21187.91791396]
 [-439073.41965801   41193.94940604   20974.13842298]
 [-434598.158095     40774.07883513   20760.35894311]
 [-430122.896577     40354.20828994   20546.57947457]
 [-425647.63510424   39934.33777179   20

2003-07-25 15:24:34.667
2003-07-25 23:08:27.460
2003-07-25 15:24:34.667
2003-07-25 23:08:27.460
[[347063.87506616 335450.22852644 130462.10122409]
 [343940.28374806 332431.16256511 129287.93642893]
 [340816.69289565 329412.09699914 128113.7718004 ]
 [337693.10250425 326393.0318251  126939.60733704]
 [334569.51256931 323373.96703917 125765.44303738]
 [331445.92308804 320354.90263721 124591.27889947]
 [328322.33405524 317335.83861679 123417.11492235]
 [325198.74546614 314316.77497363 122242.95110434]
 [322075.15731704 311297.71170446 121068.78744391]
 [318951.56960398 308278.64880571 119894.62393968]
 [315827.98232293 305259.58627343 118720.46058986]
 [312704.39546946 302240.52410418 117546.29739304]
 [309580.80903849 299221.462295   116372.13434806]
 [306457.22302631 296202.4008413  115197.97145289]
 [303333.63742867 293183.33974057 114023.80870654]
 [300210.05224264 290164.27898836 112849.64610704]
 [297086.467462   287145.21858126 111675.48365305]
 [293962.88308352 284126.15851626 110

2017-06-26 18:13:49.909
2017-06-26 23:25:22.969
2017-06-26 18:13:49.909
2017-06-26 23:25:22.969
[[392800.86820638 289594.9649795  108822.74102047]
 [389265.66223788 286988.61195552 107843.33702466]
 [385730.45633155 284382.25896913 106863.93304177]
 [382195.25048882 281775.90602127 105884.52907184]
 [378660.04470772 279169.55311123 104905.12511492]
 [375124.83898807 276563.20023832 103925.7211708 ]
 [371589.63332838 273956.84740287 102946.3172393 ]
 [368054.42772961 271350.49460328 101966.91332005]
 [364519.22219014 268744.14183995 100987.50941306]
 [360984.01670957 266137.7891129  100008.10551858]
 [357448.81128824 263531.43642092  99028.7016359 ]
 [353913.60592413 260925.0837647   98049.29776552]
 [350378.4006173  258318.73114267  97069.89390682]
 [346843.19536823 255712.37855616  96090.49006014]
 [343307.99017471 253106.02600282  95111.08622481]
 [339772.78503603 250499.6734831   94131.682401  ]
 [336237.57995349 247893.32099771  93152.27858874]
 [332702.3749246  245286.96854499  92

2021-09-25 12:36:01.343
2021-09-26 20:27:36.002
2021-09-25 12:36:01.343
2021-09-26 20:27:36.002
[[270352.35889977 376367.24339384 187769.6110549 ]
 [267919.18271089 372979.90742821 186079.6730555 ]
 [265486.00673354 369592.57240409 184389.73542121]
 [263052.83096525 366205.23831248 182699.7981486 ]
 [260619.65540516 362817.90514398 181009.8612338 ]
 [258186.48005164 359430.57288992 179319.92467383]
 [255753.30490062 356043.24154234 177629.98846528]
 [253320.12995207 352655.91109395 175940.05260548]
 [250886.95520413 349268.58153391 174250.11709014]
 [248453.78065318 345881.25285554 172560.18191668]
 [246020.60629863 342493.92504966 170870.24708149]
 [243587.43213835 339106.59810728 169180.31258139]
 [241154.25817081 335719.27201927 167490.37841243]
 [238721.08439267 332331.94677961 165800.44457263]
 [236287.91080341 328944.62237728 164110.51105738]
 [233854.73740077 325557.29880619 162420.57786456]
 [231421.56418195 322169.97605485 160730.64498967]
 [228988.39114544 318782.65411621 159

2014-09-01 16:46:22.721
2014-09-01 23:16:38.253
2014-09-01 16:46:22.721
2014-09-01 23:16:38.253
[[252750.09038866 396586.90493912 169814.37956017]
 [250475.34008849 393017.62412894 168286.05078825]
 [248200.58982438 389448.34335995 166757.72203195]
 [245925.83959442 385879.06263095 165229.39329046]
 [243651.08939946 382309.7819429  163701.064565  ]
 [241376.33923841 378740.50129408 162172.73585412]
 [239101.58911192 375171.22068506 160644.40715855]
 [236826.83901936 371601.94011557 159116.07847807]
 [234552.08895898 368032.65958506 157587.74981222]
 [232277.3389318  364463.37909228 156059.42116091]
 [230002.58893913 360894.0986383  154531.09252429]
 [227727.83897686 357324.81822151 153002.76390174]
 [225453.08904791 353755.53784209 151474.43529359]
 [223178.33915049 350186.25750005 149946.10669944]
 [220903.58928406 346616.97719365 148417.77811897]
 [218628.83944929 343047.69692475 146889.44955269]
 [216354.08964556 339478.41669208 145361.12100032]
 [214079.33987188 335909.13649321 143

2010-11-08 19:58:44.886
2010-11-08 23:35:52.466
2010-11-08 19:58:44.886
2010-11-08 23:35:52.466
[[496533.21408939  57572.14975768  11847.419149  ]
 [492064.41492325  57054.00326292  11740.7936688 ]
 [487595.61597601  56535.85671398  11634.16815799]
 [483126.8172437   56017.71011403  11527.54261804]
 [478658.01872748  55499.56346089  11420.91704803]
 [474189.22042179  54981.41675769  11314.2914495 ]
 [469720.42232862  54463.27000193  11207.66582127]
 [465251.62444204  53945.12319776  11101.04016537]
 [460782.82676408  53426.97634166  10994.41448012]
 [456314.02928808  52908.82943745  10887.78876751]
 [451845.23201671  52390.68248321  10781.16302653]
 [447376.43494439  51872.53548111  10674.53725835]
 [442907.63807076  51354.3884308   10567.91146278]
 [438438.84139469  50836.24133317  10461.28564033]
 [433970.04491249  50318.09418815  10354.65979103]
 [429501.24862301  49799.94699673  10248.03391534]
 [425032.4525238   49281.79975918  10141.40801347]
 [420563.6566129   48763.65247622  10

2018-11-03 18:44:12.780
2018-11-03 23:28:25.241
2018-11-03 18:44:12.780
2018-11-03 23:28:25.241
[[ 90824.48583594 448284.15454727 201971.9767125 ]
 [ 90007.06074998 444249.60184854 200154.23128527]
 [ 89189.63584116 440215.04925892 198336.48590051]
 [ 88372.2111052  436180.49677703 196518.74055755]
 [ 87554.78654316 432145.94440341 194700.99525684]
 [ 86737.36215144 428111.39213583 192883.24999727]
 [ 85919.93792999 424076.83997458 191065.50477915]
 [ 85102.51387334 420042.28791529 189247.75960046]
 [ 84285.08998525 416007.73596147 187430.01446296]
 [ 83467.66625968 411973.18410745 185612.269364  ]
 [ 82650.24269855 407938.632357   183794.5243056 ]
 [ 81832.81929839 403904.08070594 181976.77928562]
 [ 81015.39605805 399869.52915457 180159.03430448]
 [ 80197.972978   395834.97770464 178341.28936282]
 [ 79380.55005252 391800.42634931 176523.54445796]
 [ 78563.1272808  387765.87508905 174705.79958999]
 [ 77745.70466438 383731.32392684 172888.05476013]
 [ 76928.28219953 379696.77285856 171

2010-11-12 19:59:23.335
2010-11-12 23:35:56.331
2010-11-12 19:59:23.335
2010-11-12 23:35:56.331
[[320689.51189643 355749.84651917 143529.21925665]
 [317803.30542368 352548.0981805  142237.45647487]
 [314917.0989542  349346.3498337  140945.69368894]
 [312030.89251673 346144.60149452 139653.93090421]
 [309144.68614793 342942.85318246 138362.16812729]
 [306258.47980469 339741.10487393 137070.40535051]
 [303372.27355236 336539.35660464 135778.64258569]
 [300486.06723094 333337.60829115 134486.87980472]
 [297599.8610062  330135.86001831 133195.11703624]
 [294713.65484381 326934.11176977 131903.35427451]
 [291827.44868726 323732.36351597 130611.59151001]
 [288941.24261224 320530.61529562 129319.82875536]
 [286055.03649563 317328.86704597 128028.06599024]
 [283168.83048201 314127.11884138 126736.30323865]
 [280282.62448543 310925.37063721 125444.54048616]
 [277396.41854501 307723.62245449 124152.77773955]
 [274510.21261668 304521.87427011 122861.01499152]
 [271624.00677788 301320.12612414 121

2019-03-19 02:43:01.351
2019-03-22 14:40:17.725
2019-03-19 02:43:01.351
2019-03-22 14:40:17.725
[[  83724.30705339 -454227.18879527 -191488.76339447]
 [  82970.92731076 -450139.10111743 -189765.34634048]
 [  82217.54382777 -446051.01474607 -188041.92983919]
 [  81464.15663981 -441962.92966974 -186318.51388535]
 [  80710.76578075 -437874.84587592 -184595.09847414]
 [  79957.37128246 -433786.7633549  -182871.68360084]
 [  79203.97318149 -429698.68209356 -181148.26926029]
 [  78450.57150924 -425610.60208189 -179424.85544831]
 [  77697.16630089 -421522.52330714 -177701.44215935]
 [  76943.75758952 -417434.44575775 -175978.02938852]
 [  76190.34541065 -413346.36942279 -174254.61713129]
 [  75436.9297958  -409258.29429084 -172531.20538265]
 [  74683.51078117 -405170.22034907 -170807.79413754]
 [  73930.0883984  -401082.14758742 -169084.38339126]
 [  73176.66268331 -396994.07599288 -167360.97313875]
 [  72423.23366845 -392906.00555468 -165637.56337517]
 [  71669.80138743 -388817.93626207 -163

2010-08-27 20:31:37.336
2010-08-27 23:39:09.713
2010-08-27 20:31:37.336
2010-08-27 23:39:09.713
[[471755.6690011  159335.16555548  45381.17142245]
 [467509.87278071 157901.15145396  44972.74170023]
 [463264.07664269 156467.13735956  44564.31197621]
 [459018.28058624 155033.12327286  44155.88225075]
 [454772.48461226 153599.10919334  43747.45252355]
 [450526.68871999 152165.09512098  43339.02279469]
 [446280.89290667 150731.08105589  42930.59306429]
 [442035.09717426 149297.06699787  42522.16333222]
 [437789.30152068 147863.05294695  42113.73359862]
 [433543.50594601 146429.03890213  41705.30386301]
 [429297.71044874 144995.02486424  41296.87412587]
 [425051.9150275  143561.01083371  40888.44438745]
 [420806.11968252 142126.9968094   40480.01464724]
 [416560.32441112 140692.98279258  40071.58490597]
 [412314.52921671 139258.96878166  39663.15516271]
 [408068.7340939  137824.95477747  39254.72541818]
 [403822.93904522 136390.94077892  38846.29567172]
 [399577.14406735 134956.92678721  38

2009-11-15 16:24:40.245
2009-11-15 23:14:27.986
2009-11-15 16:24:40.245
2009-11-15 23:14:27.986
[[-485083.60501909  -42128.08180974 -113663.60756318]
 [-480717.82735369  -41748.90719956 -112640.62796834]
 [-476352.05055603  -41369.73319845 -111617.64860977]
 [-471986.27461964  -40990.55979955 -110594.66948488]
 [-467620.49953732  -40611.38699725 -109571.69059139]
 [-463254.72529933  -40232.21478663 -108548.71192753]
 [-458888.95189837  -39853.04316258 -107525.7334912 ]
 [-454523.17932785  -39473.87211846 -106502.75528   ]
 [-450157.40757814  -39094.70164967 -105479.77729194]
 [-445791.63664183  -38715.53175083 -104456.79952509]
 [-441425.86651221  -38336.36241506 -103433.82197663]
 [-437060.09718058  -37957.19363822 -102410.84464506]
 [-432694.32863617  -37578.02541591 -101387.8675287 ]
 [-428328.56087613  -37198.85773993 -100364.89062428]
 [-423962.79389015  -36819.69060589  -99341.91393023]
 [-419597.02766806  -36440.52401002  -98318.93744494]
 [-415231.26220632  -36061.35794435  -97

2004-11-15 15:28:11.024
2004-11-15 23:08:49.064
2004-11-15 15:28:11.024
2004-11-15 23:08:49.064
[[235437.58216661 404188.18949401 176639.5279153 ]
 [233318.64506841 400550.49878109 175049.77359793]
 [231199.70801848 396912.80812454 173460.01930174]
 [229080.77101684 393275.1175223  171870.26502603]
 [226961.83406383 389637.42697614 170280.51077151]
 [224842.89715832 385999.73648417 168690.75653705]
 [222723.96029937 382362.04604489 167101.00232249]
 [220605.02348578 378724.35565913 165511.24812809]
 [218486.08672059 375086.66532636 163921.49395356]
 [216367.15000015 371448.97504604 162331.73979881]
 [214248.21332461 367811.28481704 160741.98566329]
 [212129.27669567 364173.59464031 159152.23154742]
 [210010.34010869 360535.90451258 157562.47744992]
 [207891.40356779 356898.21443623 155972.72337183]
 [205772.46706921 353260.52440941 154382.96931222]
 [203653.53061336 349622.83443099 152793.21527088]
 [201534.59420151 345985.14450192 151203.46124813]
 [199415.65783048 342347.45462054 149

2022-12-11 13:46:59.702
2022-12-12 20:34:41.894
2022-12-11 13:46:59.702
2022-12-12 20:34:41.894
[[-216730.67366919  119647.43256605  434411.11909522]
 [-214780.01719409  118570.46257448  430501.42880024]
 [-212829.36291832  117493.49646991  426591.738316  ]
 [-210878.71082184  116416.53422028  422682.0476457 ]
 [-208928.06088647  115339.57578784  418772.35678931]
 [-206977.41309208  114262.6211403   414862.66574968]
 [-205026.7674197   113185.67024004  410952.97452725]
 [-203076.12384993  112108.72305343  407043.28312391]
 [-201125.48236322  111031.7795465   403133.59154211]
 [-199174.84294069  109954.83968335  399223.89978263]
 [-197224.20556203  108877.90342879  395314.207847  ]
 [-195273.57020879  107800.97074863  391404.51573712]
 [-193322.93686119  106724.04160726  387494.82345438]
 [-191372.30549952  105647.1159724   383585.13100174]
 [-189421.67610446  104570.19380575  379675.43837902]
 [-187471.04865688  103493.27507284  375765.74558806]
 [-185520.42313698  102416.35974026  371

2020-07-23 19:43:22.454
2020-07-23 23:34:20.223
2020-07-23 19:43:22.454
2020-07-23 23:34:20.223
[[427996.40591025 243152.84462416  87726.58031786]
 [424144.44178373 240964.47175193  86937.0421821 ]
 [420292.47772932 238776.09890068  86147.5040511 ]
 [416440.51374573 236587.72607026  85357.9659248 ]
 [412588.54983264 234399.35326047  84568.42780323]
 [408736.58598965 232210.98047076  83778.88968624]
 [404884.62221444 230022.60770157  82989.35157398]
 [401032.658508   227834.23495193  82199.8134661 ]
 [397180.69486886 225645.86222254  81410.27536291]
 [393328.73129719 223457.48951219  80620.73726397]
 [389476.76779014 221269.11682139  79831.19916955]
 [385624.8043505  219080.74414958  79041.66107939]
 [381772.84097534 216892.37149732  78252.12299379]
 [377920.87766373 214703.99886309  77462.58491218]
 [374068.91441691 212515.62624888  76673.04683535]
 [370216.95123291 210327.25365168  75883.50876216]
 [366364.98811132 208138.88107345  75093.97069343]
 [362513.02505034 205950.50851285  74

2017-09-27 14:26:13.235
2017-09-27 23:02:37.272
2017-09-27 14:26:13.235
2017-09-27 23:02:37.272
[[-497013.25833356  -51360.69852994  -18462.23093859]
 [-492540.14144981  -50898.45262897  -18296.07100725]
 [-488067.02469975  -50436.20673823  -18129.91107933]
 [-483593.90808123  -49973.96085697  -17963.75115456]
 [-479120.79159558  -49511.71498625  -17797.59123339]
 [-474647.67523867  -49049.46912506  -17631.43131541]
 [-470174.55901134  -48587.22327454  -17465.27140111]
 [-465701.44291151  -48124.97743301  -17299.11148974]
 [-461228.32693797  -47662.73160073  -17132.95158145]
 [-456755.21108902  -47200.4857782   -16966.79167648]
 [-452282.09536511  -46738.23996542  -16800.63177489]
 [-447808.97976333  -46275.99416208  -16634.47187641]
 [-443335.86428279  -45813.74836841  -16468.31198124]
 [-438862.74892277  -45351.50258277  -16302.15208869]
 [-434389.63368243  -44889.25680678  -16135.99219942]
 [-429916.5185594   -44427.01103894  -15969.83231283]
 [-425443.40355378  -43964.76528072  -15

2003-06-16 14:58:38.251
2003-06-16 23:05:51.761
2003-06-16 14:58:38.251
2003-06-16 23:05:51.761
[[463097.97665107 172188.94268849  76759.67983221]
 [458930.0803484  170639.23182561  76068.83923887]
 [454762.18468812 169089.52133559  75377.99878052]
 [450594.28966501 167539.81121603  74687.15845637]
 [446426.39527285 165990.10146268  73996.31826483]
 [442258.50150561 164440.39207302  73305.47820501]
 [438090.60835835 162890.68304282  72614.63827531]
 [433922.71582359 161340.97436959  71923.798475  ]
 [429754.82389727 159791.26604924  71232.9588024 ]
 [425586.93257251 158241.5580785   70542.11925647]
 [421419.04184389 156691.85045418  69851.27983594]
 [417251.15170556 155142.14317293  69160.44053971]
 [413083.26215106 153592.43623136  68469.60136649]
 [408915.373175   152042.72962606  67778.76231506]
 [404747.48477179 150493.02335395  67087.92338432]
 [400579.59693554 148943.31741101  66397.0845728 ]
 [396411.70966038 147393.61179429  65706.2458794 ]
 [392243.82294008 145843.90650046  65

2018-12-15 11:49:35.534
2018-12-15 22:46:57.413
2018-12-15 11:49:35.534
2018-12-15 22:46:57.413
[[466495.19527052  73728.25601836 164155.11062103]
 [462296.56280948  73064.52250303 162677.65370825]
 [458097.93553446  72400.79388727 161200.19857935]
 [453899.31339917  71737.07012665 159722.74521822]
 [449700.69635548  71073.35117786 158245.29360916]
 [445502.08435649  70409.63699701 156767.84373631]
 [441303.47735418  69745.92754057 155290.39558379]
 [437104.87530082  69082.22276519 153812.94913602]
 [432906.27814925  68418.52262691 152335.50437696]
 [428707.6858515   67754.82708234 150858.06129093]
 [424509.09835978  67091.13608782 149380.61986218]
 [420310.51562716  66427.44959934 147903.18007459]
 [416111.93760525  65763.76757371 146425.74191266]
 [411913.36424722  65100.08996671 144948.30536023]
 [407714.79550515  64436.41673484 143470.87040162]
 [403516.23133262  63772.74783395 141993.43702072]
 [399317.67167996  63109.08322103 140516.00520207]
 [395119.1165006   62445.42285216 139

2020-09-10 17:28:55.941
2020-09-10 23:20:53.562
2020-09-10 17:28:55.941
2020-09-10 23:20:53.562
[[419986.1353167  251056.53122935 102874.51868814]
 [416206.27004865 248797.03297052 101948.65240437]
 [412426.40465668 246537.53453031 101022.78604452]
 [408646.53915715 244278.03589389 100096.91960219]
 [404866.67354926 242018.53706548  99171.05307916]
 [401086.80783263 239759.03804883  98245.18647698]
 [397306.94200295 237499.53885031  97319.31979842]
 [393527.07605982 235240.03947279  96393.45304488]
 [389747.21001092 232980.5399121   95467.58621441]
 [385967.34386075 230721.04016599  94541.71930586]
 [382187.47759819 228461.54024839  93615.85232541]
 [378407.61123532 226202.04015002  92689.985269  ]
 [374627.74476746 223942.53987888  91764.11813992]
 [370847.87819514 221683.03943649  90838.25093898]
 [367068.01152471 219423.53881946  89912.38366485]
 [363288.14474842 217164.03803822  88986.51632163]
 [359508.27787644 214904.53708643  88060.64890668]
 [355728.41091105 212645.03596228  87

2008-12-18 18:09:56.383
2008-12-18 23:24:59.602
2008-12-18 18:09:56.383
2008-12-18 23:24:59.602
[[-215552.52698788 -396215.69641136 -215755.8951635 ]
 [-213612.52341962 -392649.71718706 -213814.07955411]
 [-211672.52079216 -389083.73917437 -211872.26438493]
 [-209732.51909089 -385517.76236218 -209930.4496517 ]
 [-207792.51831178 -381951.78673966 -207988.63535064]
 [-205852.51844293 -378385.81229609 -206046.82147779]
 [-203912.51948158 -374819.83902028 -204105.00802916]
 [-201972.52141155 -371253.86690183 -202163.19500084]
 [-200032.52422974 -367687.89592914 -200221.38238879]
 [-198092.52792571 -364121.92609185 -198279.57018908]
 [-196152.53249143 -360555.95737891 -196337.75839788]
 [-194212.53791794 -356989.9897794  -194395.94701109]
 [-192272.54419653 -353424.02328233 -192454.13602471]
 [-190332.55131896 -349858.05787675 -190512.32543491]
 [-188392.55927674 -346292.09355189 -188570.51523764]
 [-186452.5680591  -342726.1302969  -186628.70542899]
 [-184512.57766177 -339160.16810066 -184

2006-12-26 18:43:42.127
2006-12-26 23:28:22.195
2006-12-26 18:43:42.127
2006-12-26 23:28:22.195
[[-194061.6190581  -423696.6749568  -181168.80556253]
 [-192314.99999446 -419883.38979699 -179538.28379074]
 [-190568.38272519 -416070.10514857 -177907.76213125]
 [-188821.76723449 -412256.82100726 -176277.24058317]
 [-187075.15350294 -408443.53736819 -174646.71914555]
 [-185328.54151949 -404630.25422698 -173016.19781724]
 [-183581.93126364 -400816.97157922 -171385.67659751]
 [-181835.32272175 -397003.68942042 -169755.15548526]
 [-180088.71587758 -393190.40774603 -168124.63447952]
 [-178342.11071327 -389377.12655189 -166494.11357957]
 [-176595.50721347 -385563.8458332  -164863.59278426]
 [-174848.90536372 -381750.56558558 -163233.07209259]
 [-173102.305145   -377937.28580444 -161602.55150371]
 [-171355.70654246 -374124.00648555 -159972.0310167 ]
 [-169609.10954171 -370310.72762394 -158341.5106303 ]
 [-167862.51412331 -366497.44921532 -156710.99034381]
 [-166115.92027247 -362684.17125581 -155

2018-12-19 13:03:00.269
2018-12-19 22:54:18.027
2018-12-19 13:03:00.269
2018-12-19 22:54:18.027
[[-306708.72646847  353478.65389144  176021.53705806]
 [-303948.34963917  350297.34295338  174437.34198278]
 [-301187.97276823  347116.03203607  172853.14691383]
 [-298427.59584616  343934.72127372  171268.95191032]
 [-295667.21888323  340753.41051996  169684.75690779]
 [-292906.84187264  337572.09989309  168100.56195846]
 [-290146.46481653  334390.78935027  166516.36704388]
 [-287386.08771943  331209.47884417  164932.17214245]
 [-284625.71057592  328028.16845113  163347.97728816]
 [-281865.33338869  324846.85814553  161763.7824699 ]
 [-279104.95615826  321665.54790896  160179.58767921]
 [-276344.57888887  318484.23770779  158595.39290184]
 [-273584.2015731   315302.92763877  157011.19817981]
 [-270823.82421641  312121.61763173  155427.00348288]
 [-268063.44681923  308940.3076874   153842.80881083]
 [-265303.06938112  305758.99781859  152258.61416993]
 [-262542.6919045   302577.68799353  150

2011-11-26 13:10:32.356
2011-11-26 22:55:03.199
2011-11-26 13:10:32.356
2011-11-26 22:55:03.199
[[-64231.20766917 448745.47633332 210956.73053437]
 [-63653.12930462 444706.76867461 209058.12093821]
 [-63075.05088502 440668.06109238 207159.51137197]
 [-62496.97241578 436629.3535744  205260.90183058]
 [-61918.89389965 432590.64611828 203362.29231268]
 [-61340.8153286  428551.93873501 201463.68282324]
 [-60762.73671138 424513.23141497 199565.07335803]
 [-60184.65804425 420474.52415967 197666.46391761]
 [-59606.57932603 416435.81697547 195767.85450521]
 [-59028.5005587  412397.10985589 193869.24511787]
 [-58450.42174634 408358.40279651 191970.63575336]
 [-57872.34288627 404319.69579959 190072.02641293]
 [-57294.26397902 400280.98886555 188173.41709706]
 [-56716.18502355 396242.28199774 186274.80780667]
 [-56138.10602275 392203.57519037 184376.19853967]
 [-55560.02697664 388164.86844349 182477.58929607]
 [-54981.94788367 384126.16176009 180578.98007712]
 [-54403.86875051 380087.45512515 178

2002-04-23 04:45:11.002
2002-04-23 22:04:31.004
2002-04-23 04:45:11.002
2002-04-23 22:04:31.004
[[190689.14566349 406791.21110657 219451.41436377]
 [188972.94379883 403129.9736844  217476.3062932 ]
 [187256.74200216 399468.73957095 215501.19953294]
 [185540.54027222 395807.50873643 213526.09407118]
 [183824.33860788 392146.28115079 211550.98989604]
 [182108.13700776 388485.05678383 209575.88699558]
 [180391.93547194 384823.83560598 207600.78535804]
 [178675.73399853 381162.61758715 205625.68497154]
 [176959.53258754 377501.40269777 203650.58582443]
 [175243.33123788 373840.19090745 201675.48790453]
 [173527.12994876 370178.98218673 199700.39120029]
 [171810.92871888 366517.77650544 197725.29569979]
 [170094.72754788 362856.57383382 195750.20139113]
 [168378.52643329 359195.37414142 193775.10826235]
 [166662.32537688 355534.17739898 191800.01630183]
 [164946.12437654 351872.98357645 189824.92549767]
 [163229.92343108 348211.79264367 187849.83583799]
 [161513.72254043 344550.60457084 185

2009-11-16 03:01:58.879
2009-11-21 09:54:07.490
2009-11-16 03:01:58.879
2009-11-21 09:54:07.490
[[-437402.28244317 -143561.3876999  -195115.12967096]
 [-433464.96715569 -142269.21619251 -193359.16531178]
 [-429527.67184454 -140977.04819417 -191603.19942506]
 [-425590.39632463 -139684.8836762  -189847.23202657]
 [-421653.14040864 -138392.72260642 -188091.2631307 ]
 [-417715.90391439 -137100.56495658 -186335.29275324]
 [-413778.68665415 -135808.41069749 -184579.32090984]
 [-409841.48844451 -134516.25979713 -182823.34761465]
 [-405904.30910039 -133224.11222735 -181067.37288361]
 [-401967.14843607 -131931.96795598 -179311.39673117]
 [-398030.00626767 -130639.82695621 -177555.41917349]
 [-394092.88241017 -129347.68919477 -175799.44022458]
 [-390155.77668011 -128055.55464444 -174043.45990051]
 [-386218.68888962 -126763.42327106 -172287.47821488]
 [-382281.61885822 -125471.29504821 -170531.49518407]
 [-378344.56639981 -124179.16994369 -168775.5108223 ]
 [-374407.53132856 -122887.04792777 -167

2013-12-23 16:48:26.122
2013-12-23 23:16:50.575
2013-12-23 16:48:26.122
2013-12-23 23:16:50.575
[[-467384.67257315 -165283.35006645  -65066.08873494]
 [-463178.21548849 -163795.80187818  -64480.4947021 ]
 [-458971.75844979 -162308.25370151  -63894.90067406]
 [-454765.30145949 -160820.70553601  -63309.30665065]
 [-450558.8445155  -159333.15738136  -62723.71263159]
 [-446352.38761997 -157845.60923895  -62138.11861763]
 [-442145.93076956 -156358.06110653  -61552.52460771]
 [-437939.47396451 -154870.51298442  -60966.93060201]
 [-433733.0172056  -153382.96487427  -60381.33660123]
 [-429526.56049216 -151895.41677487  -59795.74260483]
 [-425320.10382313 -150407.86868599  -59210.14861275]
 [-421113.64719796 -148920.3206057   -58624.55462418]
 [-416907.19061589 -147432.77253807  -58038.96064077]
 [-412700.73407829 -145945.22447971  -57453.36666123]
 [-408494.27758282 -144457.67643163  -56867.7726859 ]
 [-404287.82113087 -142970.12839347  -56282.17871457]
 [-400081.36471885 -141482.58036572  -55

2009-01-27 16:04:00.223
2009-01-27 23:12:23.999
2009-01-27 16:04:00.223
2009-01-27 23:12:23.999
[[ 223524.5028825  -154158.17200679 -419848.69037993]
 [ 221512.77348898 -152770.71142948 -416070.04953222]
 [ 219501.0443846  -151383.25189003 -412291.4088506 ]
 [ 217489.31556703 -149995.79337892 -408512.76833306]
 [ 215477.58703274 -148608.33588785 -404734.12797986]
 [ 213465.85878035 -147220.87940592 -400955.4877871 ]
 [ 211454.13080677 -145833.4239243  -397176.84775451]
 [ 209442.40310952 -144445.96943372 -393398.2078803 ]
 [ 207430.67568633 -143058.51592425 -389619.56816253]
 [ 205418.94853362 -141671.06338766 -385840.92860101]
 [ 203407.22164983 -140283.61181346 -382062.28919293]
 [ 201395.49503212 -138896.16119286 -378283.64993732]
 [ 199383.7686777  -137508.71151599 -374505.01083243]
 [ 197372.04258414 -136121.26277402 -370726.37187721]
 [ 195360.31674883 -134733.81495726 -366947.73306958]
 [ 193348.59116919 -133346.36805612 -363169.09440827]
 [ 191336.86584274 -131958.92206144 -359

2016-06-26 01:40:24.783
2016-06-27 19:22:02.867
2016-06-26 01:40:24.783
2016-06-27 19:22:02.867
[[371617.69451058 287412.31440234 171157.88503474]
 [368273.32784963 284825.73417446 169617.54287486]
 [364928.95572987 282239.1502893  168077.19850507]
 [361584.57820061 279652.56277564 166536.85194331]
 [358240.19531164 277065.97166699 164996.5032095 ]
 [354895.80711222 274479.37699187 163456.15232144]
 [351551.41365224 271892.77878329 161915.79929894]
 [348207.01498139 269306.17707184 160375.44416063]
 [344862.61114886 266719.57188618 158835.08692437]
 [341518.20220482 264132.96326217 157294.72761127]
 [338173.78819793 261546.35122603 155754.36623807]
 [334829.36917868 258959.73581207 154214.00282501]
 [331484.94519615 256373.11704996 152673.63739054]
 [328140.5162999  253786.49497065 151133.26995364]
 [324796.0825398  251199.86960825 149592.90053439]
 [321451.6439653  248613.2409901  148052.52915014]
 [318107.20062611 246026.60915089 146512.15582146]
 [314762.75257167 243439.97412053 144

2008-12-24 18:56:05.490
2008-12-25 21:05:36.449
2008-12-24 18:56:05.490
2008-12-25 21:05:36.449
[[-11720.36850239 436240.56696784 244043.18647107]
 [-11614.89247742 432314.38089252 241846.79085261]
 [-11509.4162576  428388.19549823 239650.39548519]
 [-11403.93984431 424462.01077998 237454.00036722]
 [-11298.46324007 420535.82673037 235257.60549572]
 [-11192.98644619 416609.64334434 233061.21086916]
 [-11087.50946417 412683.46061409 230864.81648433]
 [-10982.03229579 408757.27853566 228668.42234001]
 [-10876.55494297 404831.09710181 226472.02843347]
 [-10771.07740799 400904.91630554 224275.63476196]
 [-10665.59969226 396978.7361418  222079.24132419]
 [-10560.12179752 393052.55660349 219882.84811664]
 [-10454.6437251  389126.37768519 217686.45513797]
 [-10349.16547777 385200.19938117 215490.06238607]
 [-10243.68705672 381274.02168429 213293.66985783]
 [-10138.20846316 377347.84458828 211097.27755126]
 [-10032.72970031 373421.66808778 208900.88546446]
 [ -9927.250769   369495.49217629 206

2002-07-26 11:02:51.930
2002-07-26 22:42:17.090
2002-07-26 11:02:51.930
2002-07-26 22:42:17.090
[[-475695.16266263  135990.43675873  -72258.07902766]
 [-471413.7593593   134766.53613167  -71607.77754124]
 [-467132.36032552  133542.63523545  -70957.47551756]
 [-462850.96552259  132318.73407256  -70307.17296149]
 [-458569.57491148  131094.83264539  -69656.86987794]
 [-454288.18845358  129870.93095522  -69006.56627235]
 [-450006.80610994  128647.02900467  -68356.26214951]
 [-445725.42784187  127423.12679648  -67705.95751424]
 [-441444.05361056  126199.22433108  -67055.65237231]
 [-437162.68337718  124975.32161182  -66405.34672823]
 [-432881.31710273  123751.41864066  -65755.04058709]
 [-428599.9547486   122527.51541913  -65104.73395419]
 [-424318.59627607  121303.61195036  -64454.42683416]
 [-420037.24164596  120079.70823582  -63804.11923229]
 [-415755.89081988  118855.80427731  -63153.8111538 ]
 [-411474.54375884  117631.90007772  -62503.5026034 ]
 [-407193.2004239   116407.99563892  -61

2011-04-24 14:37:47.797
2011-04-24 23:03:46.721
2011-04-24 14:37:47.797
2011-04-24 23:03:46.721
[[ -20379.92161857 -381080.97064874 -323051.34747978]
 [ -20196.48842068 -377651.20193106 -320143.87051946]
 [ -20013.05561166 -374221.43447655 -317236.39411394]
 [ -19829.62318658 -370791.66827378 -314328.91825797]
 [ -19646.19114349 -367361.90331185 -311421.44294707]
 [ -19462.75947685 -363932.13957843 -308513.96817549]
 [ -19279.32818472 -360502.37706268 -305606.49393864]
 [ -19095.89726216 -357072.61575279 -302699.02023125]
 [ -18912.46670721 -353642.85563815 -299791.54704878]
 [ -18729.03651461 -350213.09670642 -296884.07438567]
 [ -18545.60668199 -346783.33894682 -293976.60223733]
 [ -18362.17720523 -343353.58234745 -291069.13059841]
 [ -18178.74808107 -339923.82689762 -288161.6594643 ]
 [ -17995.31930536 -336494.0725852  -285254.18882951]
 [ -17811.89087541 -333064.31939897 -282346.71868929]
 [ -17628.46278697 -329634.56732762 -279439.24903865]
 [ -17445.03503692 -326204.81635988 -276

2013-12-17 20:00:15.251
2013-12-17 23:36:01.510
2013-12-17 20:00:15.251
2013-12-17 23:36:01.510
[[388683.88864663 289715.25716887 122437.13092226]
 [385185.7316677  287107.82436434 121335.19889101]
 [381687.57484469 284500.39151741 120233.26683548]
 [378189.41818273 281892.95862894 119131.33475585]
 [374691.26165634 279285.52569808 118029.40265253]
 [371193.10529062 276678.09272624 116927.47052545]
 [367694.94910139 274070.65971493 115825.53837481]
 [364196.79306829 271463.22666424 114723.60620123]
 [360698.63717625 268855.79357302 113621.67400466]
 [357200.48143002 266248.36044235 112519.74178546]
 [353702.32587013 263640.92727461 111417.80954351]
 [350204.17038599 261033.49406392 110315.8772794 ]
 [346706.01514408 258426.06082121 109213.94499319]
 [343207.85997751 255818.62753595 108112.01268505]
 [339709.70499268 253211.19421593 107010.08035535]
 [336211.55013934 250603.76085798 105908.14800415]
 [332713.3953917  247996.3274614  104806.21563188]
 [329215.24082625 245388.89403113 103

2011-12-26 19:26:18.267
2011-12-26 23:32:37.800
2011-12-26 19:26:18.267
2011-12-26 23:32:37.800
[[-222954.70162292 -408691.03790967 -182381.66603522]
 [-220948.08475891 -405012.80586687 -180740.22644304]
 [-218941.46865514 -401334.57434569 -179098.78705475]
 [-216934.85331167 -397656.3433422  -177457.34786864]
 [-214928.23871455 -393978.11285082 -175815.90888266]
 [-212921.62486124 -390299.88286726 -174174.47009505]
 [-210915.01174212 -386621.65338698 -172533.03150406]
 [-208908.39935167 -382943.42440493 -170891.59310777]
 [-206901.78768378 -379265.195917   -169250.15490451]
 [-204895.17673084 -375586.96791799 -167608.71689229]
 [-202888.56648427 -371908.74040329 -165967.2790693 ]
 [-200881.95693837 -368230.51336825 -164325.84143374]
 [-198875.34808822 -364552.28680839 -162684.40398382]
 [-196868.73992506 -360874.06071892 -161042.96671768]
 [-194862.13244021 -357195.83509487 -159401.52963347]
 [-192855.52562866 -353517.6099319  -157760.09272936]
 [-190848.91948469 -349839.38522515 -156

2003-09-19 16:36:16.316
2003-09-19 23:15:37.541
2003-09-19 16:36:16.316
2003-09-19 23:15:37.541
[[452391.3544659  201758.76763926  68084.52507427]
 [448319.72992794 199942.8488176   67471.73143002]
 [444248.10859126 198126.93261074  66858.9387365 ]
 [440176.49042626 196311.01899539  66246.1469853 ]
 [436104.87540267 194495.10794916  65633.35616846]
 [432033.26349214 192679.19944751  65020.56627695]
 [427961.65466499 190863.29346687  64407.77730226]
 [423890.0488916  189047.3899843   63794.98923614]
 [419818.44614249 187231.48897674  63182.20207024]
 [415746.84638871 185415.59042008  62569.41579584]
 [411675.24960072 183599.69429105  61956.63040449]
 [407603.65574928 181783.80056562  61343.84588744]
 [403532.06480479 179967.90922108  60731.06223657]
 [399460.47673799 178152.02023374  60118.27944328]
 [395388.89151931 176336.13358031  59505.49749915]
 [391317.30912007 174520.24923658  58892.71639532]
 [387245.72951064 172704.36717928  58279.93612342]
 [383174.15266097 170888.4873859   57

2005-12-16 10:12:16.889
2005-12-16 22:37:13.677
2005-12-16 10:12:16.889
2005-12-16 22:37:13.677
[[-459696.12025098  168907.38926953  100747.88244176]
 [-455558.85987628  167387.22060847   99841.15081352]
 [-451421.59940596  165867.05195612   98934.4191834 ]
 [-447284.33883713  164346.88337034   98027.68757734]
 [-443147.07817011  162826.71496403   97120.9560447 ]
 [-439009.81741021  161306.5464853    96214.22447535]
 [-434872.55655578  159786.37811315   95307.49294725]
 [-430735.2956046   158266.20993072   94400.7614978 ]
 [-426598.03456347  156746.04168916   93494.03001705]
 [-422460.77343198  155225.87343961   92587.29852739]
 [-418323.51220673  153705.70539314   91680.56712231]
 [-414186.25088959  152185.53746361   90773.83576399]
 [-410048.98948616  150665.36949247   89867.10438192]
 [-405911.72799404  149145.20161116   88960.37303481]
 [-401774.46641495  147625.03375274   88053.64169279]
 [-397637.20474986  146104.86593831   87146.91036531]
 [-393499.9429958   144584.69831741   86

2019-03-09 21:12:01.264
2019-03-09 23:43:12.119
2019-03-09 21:12:01.264
2019-03-09 23:43:12.119
[[-485108.73964056  110302.72834618   50030.3557386 ]
 [-480742.75915676  109309.99677227   49580.07828656]
 [-476376.7788291   108317.26541765   49129.80096362]
 [-472010.79864484  107324.53427072   48679.52376309]
 [-467644.81860766  106331.80333354   48229.24668627]
 [-463278.83871213  105339.07260071   47778.96972997]
 [-458912.85896091  104346.34207451   47328.6928954 ]
 [-454546.87935141  103353.61175105   46878.41618026]
 [-450180.89988562  102360.88163123   46428.13958524]
 [-445814.92055668  101368.15170951   45977.86310682]
 [-441448.94136526  100375.42198366   45527.58674406]
 [-437082.96230978   99382.69245334   45077.31049656]
 [-432716.98338854   98389.96311586   44627.03436268]
 [-428351.00460485   97397.23397353   44176.75834364]
 [-423985.02594918   96404.50501612   43726.48243388]
 [-419619.04742631   95411.77624859   43276.20663588]
 [-415253.06903261   94419.04766551   42

2021-03-25 12:06:45.777
2021-03-25 22:48:40.479
2021-03-25 12:06:45.777
2021-03-25 22:48:40.479
[[ 450888.30343494 -178599.60302457  121665.77637998]
 [ 446830.14371249 -176992.20666457  120570.83341078]
 [ 442771.98873591 -175384.81042787  119475.88918506]
 [ 438713.83846205 -173777.41431215  118380.94371459]
 [ 434655.69284886 -172170.01831663  117285.99701061]
 [ 430597.55185336 -170562.62243964  116191.04908468]
 [ 426539.41543314 -168955.2266801   115096.09994812]
 [ 422481.28354537 -167347.83103622  114001.14961259]
 [ 418423.15614706 -165740.43550541  112906.19809   ]
 [ 414365.03319564 -164133.04008678  111811.24539163]
 [ 410306.91464871 -162525.64477912  110716.29152883]
 [ 406248.80046344 -160918.24958136  109621.33651295]
 [ 402190.69059682 -159310.8544912   108526.38035588]
 [ 398132.58500642 -157703.45950679  107431.42306918]
 [ 394074.48364913 -156096.06462698  106336.46466427]
 [ 390016.3864826  -154488.66985114  105241.50515231]
 [ 385958.29346383 -152881.27517685  104

2016-09-24 18:14:06.964
2016-09-24 23:25:24.682
2016-09-24 18:14:06.964
2016-09-24 23:25:24.682
[[409449.3233155  264955.95163319 110226.76617671]
 [405764.27745447 262571.36352593 109234.73190339]
 [402079.23172125 260186.77504809 108242.69747074]
 [398394.18611249 257802.18620458 107250.66288082]
 [394709.14063036 255417.59699631 106258.62813403]
 [391024.09527048 253033.0074288  105266.59323278]
 [387339.05003387 250648.41750416 104274.55817796]
 [383654.00491953 248263.82722545 103282.52297083]
 [379968.95992601 245879.23659672 102290.48761319]
 [376283.91504958 243494.64562236 101298.45210693]
 [372598.87029308 241110.05430342 100306.4164525 ]
 [368913.8256515  238725.46264538  99314.38065228]
 [365228.78112689 236340.87065028  98322.344707  ]
 [361543.73671669 233956.27832176  97330.30861845]
 [357858.69242099 231571.68566266  96338.27238766]
 [354173.64823642 229187.09267756  95346.23601674]
 [350488.60416478 226802.49936815  94354.19950633]
 [346803.56020242 224417.90573995  93

2005-09-20 20:22:27.163
2005-09-20 23:38:14.698
2005-09-20 20:22:27.163
2005-09-20 23:38:14.698
[[400510.88942647 255607.9021301  155745.24181997]
 [396906.28133395 253307.43962448 154343.53999497]
 [393301.67366549 251006.97698174 152941.8380837 ]
 [389697.06641746 248706.51420317 151540.13608693]
 [386092.45958671 246406.05129087 150138.43400588]
 [382487.85317001 244105.5882452  148736.73184091]
 [378883.247161   241805.12506732 147335.02959276]
 [375278.64155811 239504.66175925 145933.32726257]
 [371674.03635573 237204.19832198 144531.62485101]
 [368069.43155631 234903.73475601 143129.92235849]
 [364464.82714617 232603.27106381 141728.21978641]
 [360860.22312537 230302.80724559 140326.51713505]
 [357255.61949253 228002.3433031  138924.81440543]
 [353651.01623923 225701.87923773 137523.11159839]
 [350046.41336891 223401.41505003 136121.4087144 ]
 [346441.81087187 221100.95074213 134719.70575464]
 [342837.20874637 218800.48631446 133318.00271953]
 [339232.60698655 216500.0217687  131

2005-12-25 08:28:00.972
2005-12-25 22:26:48.085
2005-12-25 08:28:00.972
2005-12-25 22:26:48.085
[[-427495.37615322 -246729.79429674  -79827.19080979]
 [-423647.9229259  -244509.22201061  -79108.74391031]
 [-419800.46958369 -242288.64985663  -78390.29707724]
 [-415953.01612877 -240068.07782704  -77671.85030702]
 [-412105.56256223 -237847.50592667  -76953.40360144]
 [-408258.10888463 -235626.93414259  -76234.95695499]
 [-404410.65509761 -233406.36248136  -75516.51037022]
 [-400563.2012014  -231185.79094452  -74798.06384769]
 [-396715.74719768 -228965.219522    -74079.61738327]
 [-392868.29308735 -226744.64822376  -73361.17098111]
 [-389020.83887125 -224524.07704121  -72642.72463745]
 [-385173.38455049 -222303.50597167  -71924.27835077]
 [-381325.93012648 -220082.93502843  -71205.83212683]
 [-377478.47559914 -217862.36419702  -70487.3859596 ]
 [-373631.02097074 -215641.79346991  -69768.93984529]
 [-369783.56624195 -213421.2228604   -69050.49379006]
 [-365936.11141368 -211200.65236574  -68

2007-12-27 15:53:41.041
2007-12-27 23:11:22.080
2007-12-27 15:53:41.041
2007-12-27 23:11:22.080
[[160903.8811087  437549.05385572 180723.8150112 ]
 [159455.7451849  433611.11437649 179097.30158053]
 [158007.60932106 429673.17493719 177470.78816418]
 [156559.47352219 425735.23554516 175844.27476536]
 [155111.33778477 421797.29619586 174217.76138227]
 [153663.20210773 417859.35688829 172591.24801426]
 [152215.06649464 413921.41762614 170964.73466304]
 [150766.93093812 409983.47840357 169338.22132635]
 [149318.79544723 406045.5392288  167711.70800723]
 [147870.66000968 402107.60008895 166085.19470072]
 [146422.52463514 398169.66099513 164458.68141121]
 [144974.38931608 394231.72193915 162832.16813563]
 [143526.25405568 390293.78292483 161205.65487543]
 [142078.11885303 386355.84395087 159579.14162979]
 [140629.98370534 382417.90501559 157952.62839849]
 [139181.84861511 378479.96612084 156326.11518189]
 [137733.71357965 374542.02726507 154699.6019797 ]
 [136285.57859862 370604.0884468  153

2004-11-22 16:06:21.618
2004-11-22 23:12:38.139
2004-11-22 16:06:21.618
2004-11-22 23:12:38.139
[[159275.09338641 433349.57269043 191937.32792997]
 [157841.61725169 429449.42848986 190209.89296025]
 [156408.14116341 425549.28433681 188482.45800814]
 [154974.66511524 421649.14022374 186755.02307075]
 [153541.18910921 417748.99615169 185027.5881485 ]
 [152107.71314913 413848.85212654 183300.1532439 ]
 [150674.23722523 409948.70813662 181572.71835181]
 [149240.76134783 406048.56419337 179845.28347725]
 [147807.28550833 402148.4202885  178117.84861693]
 [146373.80970991 398248.27642316 176390.41377115]
 [144940.33395201 394348.13259912 174662.97894081]
 [143506.85823417 390447.98881453 172935.54412484]
 [142073.38255644 386547.84507    171208.10932398]
 [140639.90691584 382647.70136404 169480.67453706]
 [139206.4313159  378747.55769736 167753.23976487]
 [137772.95575321 374847.41406751 166025.80500624]
 [136339.48022825 370947.27047646 164298.37026203]
 [134906.0047406  367047.12692177 162

2008-11-21 14:34:04.792
2008-11-21 23:03:24.424
2008-11-21 14:34:04.792
2008-11-21 23:03:24.424
[[-260117.22705389 -386530.91563469 -181475.87678817]
 [-257776.16692048 -383052.09910521 -179842.56976564]
 [-255435.10704224 -379573.28378263 -178209.26347643]
 [-253094.04741421 -376094.46965578 -176575.95791383]
 [-250752.9880385  -372615.65671426 -174942.65307154]
 [-248411.92890748 -369136.84494689 -173309.34894253]
 [-246070.87002131 -365658.03434238 -171676.04552038]
 [-243729.8113782  -362179.22489068 -170042.74279849]
 [-241388.75297354 -358700.41657993 -168409.44077012]
 [-239047.6948086  -355221.60940024 -166776.13942876]
 [-236706.63687742 -351742.80333963 -165142.8387676 ]
 [-234365.57917918 -348263.9983876  -163509.5387799 ]
 [-232024.5217118  -344785.19453335 -161876.23945943]
 [-229683.46447106 -341306.39176586 -160242.9407993 ]
 [-227342.40745856 -337827.59007457 -158609.64279312]
 [-225001.35066767 -334348.78944772 -156976.3454337 ]
 [-222660.29409736 -330869.98987499 -155

2017-11-27 21:13:18.710
2017-11-27 23:43:19.856
2017-11-27 21:13:18.710
2017-11-27 23:43:19.856
[[-345855.67277931  319599.80337526  168049.49711011]
 [-342742.97775783  316723.39841022  166537.04744255]
 [-339630.28271013  313846.99375449  165024.59795539]
 [-336517.58763657  310970.58940332  163512.14864585]
 [-333404.89253787  308094.18536088  161999.69951591]
 [-330292.19741357  305217.78161685  160487.2505601 ]
 [-327179.50226429  302341.37817138  158974.80177839]
 [-324066.80708984  299464.97502083  157462.35316843]
 [-320954.1118917   296588.57216586  155949.90473083]
 [-317841.41666843  293712.16959907  154437.45646117]
 [-314728.72142155  290835.76731911  152925.0083588 ]
 [-311616.02615057  287959.36532535  151412.56042307]
 [-308503.33085624  285082.96361046  149900.11265007]
 [-305390.63553849  282206.56217806  148387.66504151]
 [-302277.94019761  279330.16101962  146875.21759288]
 [-299165.24483373  276453.76013485  145362.77030353]
 [-296052.5494472   273577.35951883  143

2018-03-07 20:05:39.786
2018-03-07 23:36:33.967
2018-03-07 20:05:39.786
2018-03-07 23:36:33.967
[[-341915.19176623 -315631.60742855 -182951.54722829]
 [-338837.9468123  -312790.92616478 -181304.98527509]
 [-335760.70215872 -309950.24488629 -179658.42331023]
 [-332683.45780107 -307109.56359194 -178011.86133308]
 [-329606.2137394  -304268.88228271 -176365.29934426]
 [-326528.96997303 -301428.20095963 -174718.73734429]
 [-323451.72649369 -298587.51962054 -173072.17533216]
 [-320374.4833011  -295746.83826737 -171425.61330878]
 [-317297.24039575 -292906.1569002  -169779.0512744 ]
 [-314219.99776897 -290065.47551839 -168132.48922862]
 [-311142.75542337 -287224.79412272 -166485.92717184]
 [-308065.51335323 -284384.11271307 -164839.36510415]
 [-304988.2715539  -281543.43128862 -163192.80302506]
 [-301911.03002736 -278702.74985135 -161546.24093569]
 [-298833.7887685  -275862.06840041 -159899.67883563]
 [-295756.54777804 -273021.38693627 -158253.11672515]
 [-292679.30704597 -270180.7054584  -156

2001-11-15 18:58:47.495
2001-11-17 18:41:52.219
2001-11-15 18:58:47.495
2001-11-17 18:41:52.219
[[-413894.24707156 -256670.54404227 -113190.24757466]
 [-410169.10622358 -254360.50799583 -112171.53637217]
 [-406443.96820396 -252050.47217107 -111152.82522581]
 [-402718.83298731 -249740.43656562 -110134.114135  ]
 [-398993.70054668 -247430.40117618 -109115.40309863]
 [-395268.57085818 -245120.36600386 -108096.69211753]
 [-391543.44389528 -242810.33104502 -107077.98119047]
 [-387818.31963152 -240500.29629788 -106059.27031711]
 [-384093.19804186 -238190.2617608  -105040.55949702]
 [-380368.07909799 -235880.22743098 -104021.84872951]
 [-376642.96277761 -233570.19330721 -103003.13801426]
 [-372917.84905404 -231260.15938924 -101984.42735156]
 [-369192.73789942 -228950.12567246 -100965.71673979]
 [-365467.62929022 -226640.09215628  -99947.00617907]
 [-361742.5231992  -224330.0588395   -98928.29566923]
 [-358017.41960114 -222020.02571853  -97909.58520903]
 [-354292.31847054 -219709.99279241  -96

2005-08-21 18:15:52.823
2005-08-21 23:25:35.244
2005-08-21 18:15:52.823
2005-08-21 23:25:35.244
[[490184.47148782 -94767.11788663 -27174.16359399]
 [485772.79166159 -93914.19751391 -26929.58523763]
 [481361.11261109 -93061.27763109 -26685.00719006]
 [476949.43432853 -92208.35823286 -26440.42944782]
 [472537.7568081  -91355.43931669 -26195.85200927]
 [468126.08004236 -90502.52087697 -25951.27487095]
 [463714.40402392 -89649.60290851 -25706.69802966]
 [459302.72874698 -88796.68540914 -25462.1214838 ]
 [454891.05420357 -87943.76837297 -25217.54522985]
 [450479.3803865  -87090.85179429 -24972.96926431]
 [446067.70729005 -86237.93567179 -24728.39358605]
 [441656.03490627 -85385.01999885 -24483.8181911 ]
 [437244.36322787 -84532.1047706  -24239.24307644]
 [432832.69224876 -83679.18998426 -23994.66824019]
 [428421.02196154 -82826.27563457 -23750.09367904]
 [424009.35235879 -81973.36171621 -23505.51938979]
 [419597.68343455 -81120.44822647 -23260.94537058]
 [415186.01518112 -80267.53516002 -23

2011-12-16 11:55:32.947
2011-12-17 20:23:33.078
2011-12-16 11:55:32.947
2011-12-17 20:23:33.078
[[-111467.07058397 -445224.82617509 -198368.40209824]
 [-110463.85514581 -441217.75577605 -196583.0670976 ]
 [-109460.6400786  -437210.68684781 -194797.73271063]
 [-108457.42537972 -433203.61937916 -193012.39893255]
 [-107454.21104667 -429196.55335683 -191227.06575784]
 [-106450.99707457 -425189.48876554 -189441.73318011]
 [-105447.7834608  -421182.42559421 -187656.40119481]
 [-104444.57020119 -417175.36382747 -185871.06979549]
 [-103441.35729218 -413168.30345321 -184085.73897699]
 [-102438.14473161 -409161.24445844 -182300.40873411]
 [-101434.93251508 -405154.18682975 -180515.07906109]
 [-100431.72064018 -401147.13055456 -178729.74995261]
 [ -99428.50910264 -397140.07561803 -176944.42140269]
 [ -98425.29789951 -393133.02200752 -175159.09340605]
 [ -97422.08702654 -389125.96970999 -173373.76595706]
 [ -96418.87648109 -385118.9187125  -171588.43905044]
 [ -95415.66625932 -381111.86900055 -169

2006-12-23 18:31:56.936
2006-12-23 23:27:11.652
2006-12-23 18:31:56.936
2006-12-23 23:27:11.652
[[396884.39508025 198081.4727132  230754.19571227]
 [393312.39432876 196298.72668146 228677.40994956]
 [389740.39491895 194515.98110657 226600.62426318]
 [386168.39683849 192733.23598421 224523.83865235]
 [382596.40007572 190950.49131052 222447.05311655]
 [379024.40461859 189167.74708138 220370.26765502]
 [375452.4104542  187385.00329284 218293.48226716]
 [371880.41757017 185602.25994117 216216.69695239]
 [368308.42595604 183819.51702137 214139.91170984]
 [364736.43559733 182036.77453054 212063.12653904]
 [361164.44648516 180254.03246336 209986.34143924]
 [357592.45860592 178471.29081634 207909.55640972]
 [354020.4719473  176688.54958528 205832.77144985]
 [350448.4864966  174905.80876639 203755.98655906]
 [346876.50224273 173123.06835552 201679.20173666]
 [343304.51917247 171340.32834855 199602.41698188]
 [339732.53727436 169557.5887415  197525.63229421]
 [336160.55653611 167774.8495301  195

2017-09-26 19:45:38.285
2017-09-26 23:34:33.806
2017-09-26 19:45:38.285
2017-09-26 23:34:33.806
[[-362360.74358654  126622.09123996 -320408.48453894]
 [-359099.50402884  125482.4920381  -317524.81780228]
 [-355838.26442295  124342.89289737 -314641.15093319]
 [-352577.02476904  123203.29381651 -311757.48393227]
 [-349315.78506806  122063.69479629 -308873.81680188]
 [-346054.54532011  120924.09583563 -305990.14954257]
 [-342793.30552536  119784.49693301 -303106.48215513]
 [-339532.06568478  118644.89808938 -300222.81464157]
 [-336270.82579876  117505.29930332 -297339.14700265]
 [-333009.58586752  116365.7005744  -294455.47923988]
 [-329748.34589146  115226.1019024  -291571.81135418]
 [-326487.10587105  114086.50328639 -288688.14334682]
 [-323225.86580694  112946.90472588 -285804.47521877]
 [-319964.62569931  111807.30622014 -282920.80697155]
 [-316703.38554871  110667.70776868 -280037.13860616]
 [-313442.14535564  109528.10937151 -277153.47012395]
 [-310180.90512033  108388.51102749 -274

2016-10-22 10:16:17.068
2016-10-22 22:37:37.575
2016-10-22 10:16:17.068
2016-10-22 22:37:37.575
[[432594.61063629 213808.26361133 130952.7538578 ]
 [428701.07523924 211884.05814344 129774.22101537]
 [424807.5451107  209959.85094859 128595.68712598]
 [420914.02020377 208035.64204391 127417.15219967]
 [417020.50047117 206111.43144604 126238.61624632]
 [413126.98586673 204187.21917023 125060.07927522]
 [409233.47634396 202263.00523195 123881.54129573]
 [405339.97185594 200338.78964782 122703.00231774]
 [401446.47235572 198414.57243419 121524.46235096]
 [397552.97779596 196490.35360705 120345.92140496]
 [393659.48813045 194566.13318271 119167.37948953]
 [389766.00331259 192641.91117594 117988.83661371]
 [385872.52329507 190717.68760371 116810.29278755]
 [381979.04803082 188793.46248204 115631.74802062]
 [378085.57747304 186869.23582712 114453.2023226 ]
 [374192.11157483 184945.00765485 113274.65570308]
 [370298.65028948 183020.77798023 112096.10817123]
 [366405.19357005 181096.54682018 110

2004-12-24 20:12:03.665
2004-12-24 23:37:12.356
2004-12-24 20:12:03.665
2004-12-24 23:37:12.356
[[-472857.18175033 -130483.59302536  -96853.3717833 ]
 [-468601.45810831 -129309.2431244   -95981.69339633]
 [-464345.73481274 -128134.89318598  -95110.01497746]
 [-460090.01186144 -126960.54321018  -94238.33652681]
 [-455834.28925088 -125786.1931975   -93366.65804481]
 [-451578.5669792  -124611.84314734  -92494.97953129]
 [-447322.84504312 -123437.49306127  -91623.30098706]
 [-443067.12343687 -122263.14293931  -90751.62241232]
 [-438811.40215972 -121088.79278208  -89879.94380748]
 [-434555.68120843 -119914.44258897  -89008.26517234]
 [-430299.96057832 -118740.09236164  -88136.58650788]
 [-426044.24026823 -117565.74209907  -87264.90781371]
 [-421788.52027306 -116391.39180233  -86393.22909046]
 [-417532.80059311 -115217.04147121  -85521.55033818]
 [-413277.08121997 -114042.69110747  -84649.87155781]
 [-409021.36215422 -112868.34071041  -83778.19274916]
 [-404765.64339155 -111693.99028039  -82

2014-11-07 15:01:27.291
2014-11-07 23:06:08.678
2014-11-07 15:01:27.291
2014-11-07 23:06:08.678
[[156174.56744561 435589.29112595 189398.93656236]
 [154768.99719918 431668.99229509 187694.3483088 ]
 [153363.42699707 427748.69352132 185989.7600776 ]
 [151957.85683668 423828.39480162 184285.17186743]
 [150552.28672084 419908.09613907 182580.58367965]
 [149146.71664584 415987.79752994 180875.99551243]
 [147741.14661294 412067.49897587 179171.40736687]
 [146335.57662165 408147.20047557 177466.8192423 ]
 [144930.00667068 404226.90202743 175762.2311379 ]
 [143524.43676195 400306.60363328 174057.64305466]
 [142118.86689088 396386.30528915 172353.05499095]
 [140713.29706207 392466.00699896 170648.46694821]
 [139307.72727203 388545.70875901 168943.87892523]
 [137902.15751958 384625.41056865 167239.29092136]
 [136496.58780661 380705.11242801 165534.70293692]
 [135091.01813167 376784.81433821 163830.11497235]
 [133685.44849682 372864.51629847 162125.52702716]
 [132279.87889701 368944.21830511 160

2009-12-19 20:04:31.016
2009-12-19 23:36:27.077
2009-12-19 20:04:31.016
2009-12-19 23:36:27.077
[[-143887.7046386  -416593.48105891 -236107.58334327]
 [-142592.7103672  -412844.14244463 -233982.61668502]
 [-141297.71629888 -409094.80395526 -231857.65009621]
 [-140002.72242929 -405345.46558902 -229732.68357566]
 [-138707.72875714 -401596.12734288 -227607.7171219 ]
 [-137412.73528478 -397846.78922248 -225482.75073786]
 [-136117.74200632 -394097.45122072 -223357.78441975]
 [-134822.74892089 -390348.1133381  -221232.81816785]
 [-133527.75602598 -386598.77557319 -219107.85198122]
 [-132232.76331928 -382849.43792427 -216982.88585906]
 [-130937.77080332 -379100.10039373 -214857.91980252]
 [-129642.77847123 -375350.76297636 -212732.95380896]
 [-128347.78632334 -371601.42567316 -210607.98787867]
 [-127052.7943548  -367852.0884797  -208483.0220094 ]
 [-125757.80257091 -364102.75140125 -206358.05620399]
 [-124462.81096159 -360353.41442984 -204233.09045793]
 [-123167.81953242 -356604.07757038 -202

2009-05-26 19:59:52.885
2009-05-26 23:35:59.273
2009-05-26 19:59:52.885
2009-05-26 23:35:59.273
[[-498043.47750378  -41808.36224939  -14325.52528135]
 [-493561.09005272  -41432.08798553  -14196.59595249]
 [-489078.70264488  -41055.81370759  -14067.66661727]
 [-484596.31527722  -40679.53941526  -13938.73727563]
 [-480113.92795694  -40303.26510733  -13809.80792696]
 [-475631.54067385  -39926.99078625  -13680.87857243]
 [-471149.15343589  -39550.7164506   -13551.94921127]
 [-466666.76623404  -39174.44210222  -13423.01984449]
 [-462184.3790794   -38798.16773821  -13294.09047069]
 [-457701.99196345  -38421.89336169  -13165.16109116]
 [-453219.60488415  -38045.61897133  -13036.23170561]
 [-448737.2178461   -37669.34456769  -12907.30231395]
 [-444254.8308481   -37293.07014988  -12778.37291602]
 [-439772.44389266  -36916.79571919  -12649.44351228]
 [-435290.05697006  -36540.52127603  -12520.51410293]
 [-430807.6700902   -36164.24681905  -12391.58468741]
 [-426325.28324574  -35787.97235028  -12

2017-07-24 19:14:16.626
2017-07-24 23:31:25.632
2017-07-24 19:14:16.626
2017-07-24 23:31:25.632
[[ 4.98336036e+05 -4.06923307e+04  2.45430741e+03]
 [ 4.93851009e+05 -4.03260862e+04  2.43222743e+03]
 [ 4.89365981e+05 -3.99598421e+04  2.41014720e+03]
 [ 4.84880955e+05 -3.95935984e+04  2.38806674e+03]
 [ 4.80395928e+05 -3.92273551e+04  2.36598605e+03]
 [ 4.75910902e+05 -3.88611121e+04  2.34390513e+03]
 [ 4.71425876e+05 -3.84948696e+04  2.32182398e+03]
 [ 4.66940851e+05 -3.81286274e+04  2.29974261e+03]
 [ 4.62455825e+05 -3.77623855e+04  2.27766101e+03]
 [ 4.57970800e+05 -3.73961440e+04  2.25557919e+03]
 [ 4.53485776e+05 -3.70299029e+04  2.23349715e+03]
 [ 4.49000751e+05 -3.66636621e+04  2.21141489e+03]
 [ 4.44515727e+05 -3.62974217e+04  2.18933242e+03]
 [ 4.40030704e+05 -3.59311816e+04  2.16724974e+03]
 [ 4.35545680e+05 -3.55649419e+04  2.14516684e+03]
 [ 4.31060657e+05 -3.51987025e+04  2.12308373e+03]
 [ 4.26575634e+05 -3.48324635e+04  2.10100042e+03]
 [ 4.22090612e+05 -3.44662248e+04  2.

2008-12-16 23:41:27.209
2008-12-17 21:34:08.667
2008-12-16 23:41:27.209
2008-12-17 21:34:08.667
[[197342.59340066 402281.21314186 221869.65933836]
 [195566.51009378 398660.66685951 219872.82703507]
 [193790.42681919 395040.12106103 217875.99491447]
 [192014.34357657 391419.57574153 215879.1629746 ]
 [190238.26036617 387799.0308969  213882.33121407]
 [188462.17718704 384178.48652315 211885.49963135]
 [186686.09403871 380557.94261527 209888.66822445]
 [184910.01092145 376937.39916915 207891.83699197]
 [183133.92783499 373316.85618043 205895.00593206]
 [181357.84477866 369696.31364512 203898.17504352]
 [179581.76175159 366075.77155769 201901.34432381]
 [177805.67875549 362455.22991556 199904.51377246]
 [176029.59578802 358834.68871266 197907.68338683]
 [174253.51284972 355214.14794517 195910.85316557]
 [172477.42993964 351593.60760832 193914.02310693]
 [170701.34705894 347973.06769884 191917.19320965]
 [168925.26420535 344352.52821201 189920.36347187]
 [167149.18137923 340731.98914123 187

2019-06-20 07:47:47.048
2019-06-20 22:22:46.650
2019-06-20 07:47:47.048
2019-06-20 22:22:46.650
[[491245.36607587  87881.28992045  30915.16731459]
 [486824.16205674  87090.35446757  30636.92908001]
 [482402.95804828  86299.41914183  30358.69090062]
 [477981.75404727  85508.48393947  30080.45277479]
 [473560.55005431  84717.5488587   29802.21470115]
 [469139.34607428  83926.61390597  29523.97668308]
 [464718.14210182  83135.67907512  29245.73871765]
 [460296.93813723  82344.7443611   28967.50080279]
 [455875.73418498  81553.80977291  28689.26294219]
 [451454.53023881  80762.87529904  28411.02513117]
 [447033.32630301  79971.94094455  28132.78737167]
 [442612.1223762   79181.00670624  27854.54966247]
 [438190.9184587   78390.07258254  27576.31200284]
 [433769.71454954  77599.13857478  27298.0743933 ]
 [429348.51064777  76808.2046774   27019.8368316 ]
 [424927.30675215  76017.27089006  26741.59931719]
 [420506.10287023  75226.337219    26463.36185321]
 [416084.89899492  74435.40365428  26

2004-08-23 04:30:34.514
2004-08-23 22:03:03.350
2004-08-23 04:30:34.514
2004-08-23 22:03:03.350
[[371833.86595637 288868.44234627 168211.36688536]
 [368487.35321051 286268.61653978 166697.46281928]
 [365140.84082645 283668.79111254 165183.55886674]
 [361794.3288005  281068.96606189 163669.65502694]
 [358447.81712967 278469.14138317 162155.75129837]
 [355101.30581027 275869.31707418 160641.84768061]
 [351754.79483944 273269.49313027 159127.94417222]
 [348408.28421342 270669.66954941 157614.04077259]
 [345061.77392936 268069.84632725 156100.13748036]
 [341715.26398337 265470.0234592  154586.23429391]
 [338368.75437361 262870.20094413 153072.33121325]
 [335022.24509478 260270.37877738 151558.42823696]
 [331675.73614466 257670.55695599 150044.52536418]
 [328329.22751963 255070.73547548 148530.62259331]
 [324982.71921694 252470.91433328 147016.71992378]
 [321636.21123302 249871.09352565 145502.81735434]
 [318289.70356411 247271.27304888 143988.91488409]
 [314943.19620764 244671.45289993 142

2021-10-13 17:18:29.112
2021-10-13 23:19:50.886
2021-10-13 17:18:29.112
2021-10-13 23:19:50.886
[[-498943.77609682  -31217.86216363   -9006.45702827]
 [-494453.28482181  -30936.90155593   -8925.3989497 ]
 [-489962.79361361  -30655.94095263   -8844.34087254]
 [-485472.30247229  -30374.98035461   -8763.28279725]
 [-480981.81139952  -30094.01976019   -8682.22472313]
 [-476491.32039016  -29813.05917105   -8601.16665082]
 [-472000.82944632  -29532.09858707   -8520.10858035]
 [-467510.33856618  -29251.13800606   -8439.05051075]
 [-463019.84775043  -28970.17743078   -8357.99244326]
 [-458529.35699785  -28689.21685907   -8276.93437687]
 [-454038.86630809  -28408.25629184   -8195.87631203]
 [-449548.37567919  -28127.29573002   -8114.81824914]
 [-445057.88511217  -27846.33517054   -8033.7601869 ]
 [-440567.39460611  -27565.37461674   -7952.70212671]
 [-436076.9041599   -27284.41406661   -7871.64406772]
 [-431586.41377318  -27003.45352063   -7790.58601016]
 [-427095.92344582  -26722.49297825   -7

2023-11-20 09:13:40.343
2023-11-20 22:31:22.007
2023-11-20 09:13:40.343
2023-11-20 22:31:22.007
[[ 154533.38159302 -435921.99121076 -189977.85890555]
 [ 153142.58621418 -431998.6912607  -188268.05736989]
 [ 151751.79071796 -428075.39143097 -186558.25588453]
 [ 150360.99510807 -424152.09171331 -184848.45444605]
 [ 148970.19938493 -420228.79210913 -183138.65305489]
 [ 147579.40355003 -416305.49261594 -181428.85170978]
 [ 146188.60760218 -412382.19323719 -179719.0504126 ]
 [ 144797.81154412 -408458.89396828 -178009.24916115]
 [ 143407.01537749 -404535.59480655 -176299.44795468]
 [ 142016.21910331 -400612.29575229 -174589.64679295]
 [ 140625.42272058 -396688.99680662 -172879.84567669]
 [ 139234.62623224 -392765.69796824 -171170.04460484]
 [ 137843.82963946 -388842.39923227 -169460.24357596]
 [ 136453.03294232 -384919.10060012 -167750.44259033]
 [ 135062.23614106 -380995.80207479 -166040.64164934]
 [ 133671.43923897 -377072.5036484  -164330.84074962]
 [ 132280.64223713 -373149.20532036 -162

2017-12-26 19:29:26.505
2017-12-26 23:32:56.645
2017-12-26 19:29:26.505
2017-12-26 23:32:56.645
[[-414110.48095158 -259054.05476683 -106787.51201404]
 [-410383.4616788  -256722.57221749 -105826.42699421]
 [-406656.44312242 -254391.08958595 -104865.3419144 ]
 [-402929.42527544 -252059.60687339 -103904.25677535]
 [-399202.40813172 -249728.12408012 -102943.17157741]
 [-395475.39168549 -247396.64120689 -101982.0863211 ]
 [-391748.37592945 -245065.15825482 -101021.00100717]
 [-388021.36085385 -242733.67522584 -100059.91563673]
 [-384294.34645915 -240402.19211811  -99098.83020903]
 [-380567.33273268 -238070.7089344   -98137.74472569]
 [-376840.31967264 -235739.22567442  -97176.65918662]
 [-373113.3072708  -233407.74233922  -96215.57359257]
 [-369386.2955187  -231076.25893015  -95254.48794441]
 [-365659.28441265 -228744.77544709  -94293.40224225]
 [-361932.27394411 -226413.29189181  -93332.31648706]
 [-358205.264108   -224081.80826405  -92371.23067899]
 [-354478.2548967  -221750.3245651   -91

2019-12-24 12:48:14.222
2019-12-24 22:52:49.378
2019-12-24 12:48:14.222
2019-12-24 22:52:49.378
[[495750.52799734 -50749.75680491 -40701.80396197]
 [491288.71083623 -50292.9949805  -40335.47997814]
 [486826.89551562 -49836.23355417 -39969.15621788]
 [482365.08201921 -49379.47252193 -39602.832679  ]
 [477903.27033025 -48922.71188049 -39236.50935966]
 [473441.46043202 -48465.95162623 -38870.18625777]
 [468979.65230796 -48009.19175464 -38503.86337092]
 [464517.8459411  -47552.43226282 -38137.54069745]
 [460056.04131472 -47095.67314692 -37771.21823513]
 [455594.23841229 -46638.91440316 -37404.89598192]
 [451132.43721724 -46182.1560275  -37038.57393559]
 [446670.63771281 -45725.39801633 -36672.25209413]
 [442208.83988205 -45268.64036678 -36305.9304558 ]
 [437747.04370841 -44811.88307427 -35939.60901816]
 [433285.2491751  -44355.12613539 -35573.28777928]
 [428823.45626578 -43898.36954646 -35206.96673707]
 [424361.66496345 -43441.61330368 -34840.64588949]
 [419899.87525135 -42984.85740356 -34

2006-09-03 16:51:27.522
2006-09-03 23:17:08.743
2006-09-03 16:51:27.522
2006-09-03 23:17:08.743
[[285342.44008479 377350.31917179 161823.88783026]
 [282774.34928223 373954.15619612 160367.46863163]
 [280206.25874534 370557.99353054 158911.04956265]
 [277638.16847649 367161.83117399 157454.63062279]
 [275070.07847106 363765.66912267 155998.21181053]
 [272501.98872378 360369.50737354 154541.79312453]
 [269933.8992376  356973.34592426 153085.3745639 ]
 [267365.81000477 353577.1847719  151628.95612738]
 [264797.72102794 350181.02391377 150172.53781381]
 [262229.63230214 346784.86334729 148716.11962214]
 [259661.54382381 343388.70306879 147259.70155084]
 [257093.45559135 339992.54307613 145803.28359905]
 [254525.36760297 336596.38336617 144346.86576539]
 [251957.27985719 333200.2239368  142890.44804895]
 [249389.19234878 329804.06478414 141434.03044826]
 [246821.10507727 326407.90590608 139977.61296235]
 [244253.01803935 323011.74729961 138521.19558991]
 [241684.93123415 319615.58896205 137

2020-05-23 20:29:53.998
2020-05-23 23:38:59.391
2020-05-23 20:29:53.998
2020-05-23 23:38:59.391
[[492302.08937174  87199.94928089   5946.93120518]
 [487871.36968368  86415.15034337   5893.4090945 ]
 [483440.65011582  85630.35140438   5839.88697677]
 [479009.93066189  84845.55246693   5786.36485365]
 [474579.21132317  84060.75352927   5732.84272431]
 [470148.49209848  83275.95459187   5679.32058905]
 [465717.77298746  82491.15565397   5625.79844747]
 [461287.05398825  81706.35671678   5572.27630027]
 [456856.33509988  80921.55777969   5518.75414722]
 [452425.61632138  80136.75884207   5465.23198807]
 [447994.89765179  79351.9599047    5411.70982325]
 [443564.17908987  78567.16096818   5358.1876531 ]
 [439133.46063411  77782.362031     5304.66547697]
 [434702.74228397  76997.56309444   5251.14329553]
 [430272.0240407   76212.76415643   5197.62110769]
 [425841.30589879  75427.96522002   5144.09891523]
 [421410.5878593   74643.16628355   5090.57671727]
 [416979.86992103  73858.36734705   5

2013-05-05 20:00:14.409
2013-05-05 23:36:01.434
2013-05-05 20:00:14.409
2013-05-05 23:36:01.434
[[-499613.08264089   16376.76954186   10913.98517771]
 [-495116.56542271   16229.37774749   10815.75894577]
 [-490620.04826069   16081.98597868   10717.53272507]
 [-486123.53115255   15934.59423584   10619.30651589]
 [-481627.01410025   15787.20251843   10521.0803181 ]
 [-477130.49709958   15639.81082503   10422.85413076]
 [-472633.98015344   15492.41915794   10324.62795511]
 [-468137.46325868   15345.02751477   10226.40179002]
 [-463640.94641584   15197.63589579   10128.17563567]
 [-459144.42962754   15050.24430205   10029.94949248]
 [-454647.9128862    14902.85273121    9931.72335946]
 [-450151.39619809   14755.4611849     9833.49723718]
 [-445654.87955987   14608.06966165    9735.27112517]
 [-441158.36297059   14460.67816174    9637.04502344]
 [-436661.84643036   14313.28668493    9538.81893194]
 [-432165.32994074   14165.89523114    9440.59285071]
 [-427668.81349671   14018.50379916    9

2024-09-24 21:54:12.200
2024-09-25 21:23:24.953
2024-09-24 21:54:12.200
2024-09-25 21:23:24.953
[[ 440314.79118282 -214393.72638571 -100791.48373307]
 [ 436351.86924425 -212464.00447491  -99884.28496797]
 [ 432388.95002109 -210534.28754753  -98977.08831744]
 [ 428426.03349054 -208604.57555908  -98069.89376253]
 [ 424463.11962929 -206674.86846203  -97162.70128322]
 [ 420500.20841229 -204745.16621944  -96255.51086372]
 [ 416537.29981744 -202815.46877939  -95348.32248205]
 [ 412574.39382038 -200885.77610296  -94441.13612166]
 [ 408611.49039832 -198956.08813965  -93533.9517612 ]
 [ 404648.5895265  -197026.40484902  -92626.76938352]
 [ 400685.6911824  -195096.72618571  -91719.58896923]
 [ 396722.7953417  -193167.05210268  -90812.41049851]
 [ 392759.90198085 -191237.38255921  -89905.23395404]
 [ 388797.01107645 -189307.71750635  -88998.05931503]
 [ 384834.12260425 -187378.05690375  -88090.88656442]
 [ 380871.2365407  -185448.40070429  -87183.71568216]
 [ 376908.35286248 -183518.74886355  -86

2002-04-24 05:13:01.367
2002-04-24 22:07:18.043
2002-04-24 05:13:01.367
2002-04-24 22:07:18.043
[[173618.07002917 415000.21583882 218246.79037295]
 [172055.50670526 411265.10244778 216282.52518798]
 [170492.94347245 407529.99223149 214318.26127873]
 [168930.38033083 403794.88516173 212353.99863386]
 [167367.81727861 400059.78120935 210389.73724163]
 [165805.25431465 396324.68034577 208425.47709055]
 [164242.69143844 392589.58254275 206461.21816936]
 [162680.12864737 388854.48777074 204496.96046612]
 [161117.56594334 385119.3960022  202532.70396981]
 [159555.00332198 381384.30720735 200568.44866839]
 [157992.44078432 377649.22135806 198604.19455065]
 [156429.87832821 373914.13842559 196639.94160499]
 [154867.31595331 370179.05838072 194675.68981968]
 [153304.75365859 366443.98119575 192711.43918362]
 [151742.1914417  362708.90684074 190747.18968472]
 [150179.62930346 358973.8352882  188782.94131204]
 [148617.06724107 355238.76650834 186818.69405352]
 [147054.50525526 351503.70047331 184

2013-09-10 17:12:03.720
2013-09-10 23:19:12.357
2013-09-10 17:12:03.720
2013-09-10 23:19:12.357
[[-498956.58719385  -29388.92526776  -13382.83561897]
 [-494465.97836411  -29124.42489821  -13262.39011402]
 [-489975.36960369  -28859.92453548  -13141.94461124]
 [-485484.76091158  -28595.42417914  -13021.49911039]
 [-480994.1522873   -28330.92382726  -12901.05361067]
 [-476503.54373044  -28066.42348191  -12780.60811301]
 [-472012.93524075  -27801.92314255  -12660.16261713]
 [-467522.3268165   -27537.42280802  -12539.71712263]
 [-463031.71845782  -27272.92247993  -12419.27163003]
 [-458541.11016512  -27008.42215666  -12298.8261389 ]
 [-454050.50193536  -26743.92183933  -12178.38064951]
 [-449559.89376938  -26479.4215275   -12057.93516177]
 [-445069.28566718  -26214.92122     -11937.48967524]
 [-440578.67762637  -25950.42091882  -11817.04419057]
 [-436088.06964755  -25685.92062199  -11696.59870714]
 [-431597.46173     -25421.42033148  -11576.15322575]
 [-427106.85387242  -25156.92004529  -11

2008-10-25 02:43:17.142
2008-10-26 19:28:19.571
2008-10-25 02:43:17.142
2008-10-26 19:28:19.571
[[306050.34848306 302110.20576471 255074.79582271]
 [303295.89612186 299391.15972334 252779.1088565 ]
 [300541.44381383 296672.11522388 250483.42232585]
 [297786.99155924 293953.07225114 248187.73622605]
 [295032.53935763 291234.03079182 245892.05055362]
 [292278.08720762 288514.99083167 243596.36530417]
 [289523.63510874 285795.95235634 241300.68047386]
 [286769.18306112 283076.91535228 239004.99605882]
 [284014.73106435 280357.87980646 236709.31205571]
 [281260.27911732 277638.84570348 234413.62845945]
 [278505.82721907 274919.81302977 232117.94526672]
 [275751.37536976 272200.78177029 229822.26247323]
 [272996.92356855 269481.75191325 227526.58007568]
 [270242.47181526 266762.72344369 225230.89806956]
 [267488.02010876 264043.69634688 222935.21645108]
 [264733.56844929 261324.67060924 220639.53521621]
 [261979.11683559 258605.646218   218343.8543615 ]
 [259224.66526738 255886.62315792 216

2015-06-26 09:05:38.144
2015-06-26 22:30:33.756
2015-06-26 09:05:38.144
2015-06-26 22:30:33.756
[[  5135.48405176 448561.01270455 220832.65117371]
 [  5089.26279828 444523.96197361 218845.15712196]
 [  5043.04159656 440486.91141629 216857.66313943]
 [  4996.82044859 436449.86103433 214870.16922691]
 [  4950.59935218 432412.81082517 212882.67538333]
 [  4904.37830664 428375.76078582 210895.1816074 ]
 [  4858.15731271 424338.71091568 208907.68789905]
 [  4811.93636994 420301.66121298 206920.19425747]
 [  4765.71547616 416264.61167574 204932.70068187]
 [  4719.49463265 412227.5623042  202945.20717239]
 [  4673.27383819 408190.51309502 200957.71372768]
 [  4627.05309246 404153.46404696 198970.22034726]
 [  4580.83239445 400116.41515768 196982.7270301 ]
 [  4534.61174431 396079.36642706 194995.2337763 ]
 [  4488.39114225 392042.31785369 193007.74058527]
 [  4442.17058624 388005.26943469 191020.24745578]
 [  4395.95007639 383968.22116786 189032.7543869 ]
 [  4349.72961271 379931.1730538  187

2010-08-19 18:24:50.663
2010-08-19 23:26:29.053
2010-08-19 18:24:50.663
2010-08-19 23:26:29.053
[[170790.81550446 288619.80804789 370849.97113709]
 [169253.65952061 286022.18807791 367512.3127609 ]
 [167716.50461496 283424.56928594 364174.65468274]
 [166179.35077827 280826.95166117 360836.99690005]
 [164642.1980011  278229.33519334 357499.33941036]
 [163105.04627208 275631.71987164 354161.68221059]
 [161567.8955832  273034.10568546 350824.02529844]
 [160030.74592303 270436.49262448 347486.36867093]
 [158493.59728222 267838.8806781  344148.71232542]
 [156956.44965129 265241.26983544 340811.0562593 ]
 [155419.30302046 262643.66008599 337473.40046997]
 [153882.15737954 260046.05141948 334135.74495471]
 [152345.01272023 257448.44382499 330798.08971115]
 [150807.86903052 254850.83729206 327460.43473606]
 [149270.72630204 252253.23180997 324122.78002712]
 [147733.58452404 249655.62736838 320785.1255814 ]
 [146196.44368705 247058.02395657 317447.47139646]
 [144659.30378152 244460.42156373 314

2020-03-24 11:27:45.674
2020-03-24 22:44:46.525
2020-03-24 11:27:45.674
2020-03-24 22:44:46.525
[[ 48447.58800102 456896.33784705 197228.00345373]
 [ 48011.55983194 452784.26534235 195452.9491201 ]
 [ 47575.53167224 448672.19310069 193677.89489859]
 [ 47139.50352102 444560.12111998 191902.84078813]
 [ 46703.47537927 440448.04939801 190127.7867879 ]
 [ 46267.44724618 436335.97793233 188352.73289686]
 [ 45831.41912166 432223.90672088 186577.67911407]
 [ 45395.39100578 428111.83576053 184802.62543821]
 [ 44959.36289831 423999.76504964 183027.5718686 ]
 [ 44523.33479937 419887.69458503 181252.51840386]
 [ 44087.30670843 415775.62436467 179477.46504313]
 [ 43651.2786261  411663.5543865  177702.41178554]
 [ 43215.250552   407551.48464823 175927.35863021]
 [ 42779.22248594 403439.41514617 174152.30557537]
 [ 42343.19442736 399327.34587938 172377.25262076]
 [ 41907.16637725 395215.2768448  170602.19976506]
 [ 41471.13833489 391103.20804065 168827.14700747]
 [ 41035.11030009 386991.13946372 167

2008-12-26 11:41:03.217
2008-12-26 22:46:06.263
2008-12-26 11:41:03.217
2008-12-26 22:46:06.263
[[-401354.32959564 -281595.0046556   -98079.00302482]
 [-397742.14711381 -279060.64984524  -97196.29166624]
 [-394129.96459536 -276526.29509282  -96313.58033586]
 [-390517.78204831 -273991.9404512   -95430.86905658]
 [-386905.59947231 -271457.58591515  -94548.15782601]
 [-383293.41686259 -268923.23145092  -93665.44662955]
 [-379681.23422599 -266388.87709433  -92782.73548278]
 [-376069.05155735 -263854.52281988  -91900.02437434]
 [-372456.86886007 -261320.16863966  -91017.31331   ]
 [-368844.68613586 -258785.81456232  -90134.6022926 ]
 [-365232.50337781 -256251.46054465  -89251.89130452]
 [-361620.32059526 -253717.10664093  -88369.18036836]
 [-358008.13778308 -251182.75281358  -87486.46946806]
 [-354395.95494202 -248648.39906782  -86603.75860602]
 [-350783.77207434 -246114.0454129   -85721.04778594]
 [-347171.58917946 -243579.69184941  -84838.33700824]
 [-343559.40625563 -241045.33835679  -83

2012-11-25 20:53:49.253
2012-11-25 23:41:22.918
2012-11-25 20:53:49.253
2012-11-25 23:41:22.918
[[ 38750.63232003 458087.61124703 196607.92336512]
 [ 38401.86532407 453964.81627551 194838.44937836]
 [ 38053.09864044 449842.02156389 193068.9755004 ]
 [ 37704.33226769 445719.22711064 191299.50173065]
 [ 37355.56620419 441596.43291447 189530.02806857]
 [ 37006.80044682 437473.6389731  187760.55451318]
 [ 36658.03498942 433350.84528171 185991.08106245]
 [ 36309.26983173 429228.05183958 184221.60771614]
 [ 35960.50497271 425105.2586457  182452.13447374]
 [ 35611.74040784 420982.46569613 180682.66133367]
 [ 35262.97613361 416859.67298867 178913.18829497]
 [ 34914.21214451 412736.88051955 177143.71535613]
 [ 34565.44844346 408614.0882892  175374.24251724]
 [ 34216.68502527 404491.29629444 173604.76977699]
 [ 33867.92188689 400368.50453222 171835.29713415]
 [ 33519.15902221 396245.71299885 170065.82458709]
 [ 33170.3964345  392122.92169532 168296.35213634]
 [ 32821.63411798 388000.13061744 166

2019-12-13 23:48:52.478
2019-12-26 14:22:03.775
2019-12-13 23:48:52.478
2019-12-26 14:22:03.775
[[  35981.24701756 -412747.74883926 -279902.61808318]
 [  35659.32500067 -409029.43175709 -277382.48856732]
 [  35337.35134315 -405311.21449816 -274862.38874504]
 [  35015.32652444 -401593.096228   -272342.318371  ]
 [  34693.25102061 -397875.07611215 -269822.27719989]
 [  34371.12530953 -394157.15331626 -267302.26498654]
 [  34048.9498691  -390439.32700044 -264782.28148374]
 [  33726.72517565 -386721.59632784 -262262.32644549]
 [  33404.45170689 -383003.96045661 -259742.39962399]
 [  33082.12994039 -379286.41854721 -257222.50077221]
 [  32759.76035225 -375568.96975613 -254702.62964183]
 [  32437.34341916 -371851.61323977 -252182.78598434]
 [  32114.87961775 -368134.34815323 -249662.9695513 ]
 [  31792.36942479 -364417.17365056 -247143.18009326]
 [  31469.8133162  -360700.08888328 -244623.41736022]
 [  31147.21176767 -356983.09300286 -242103.68110216]
 [  30824.56525597 -353266.1851598  -239

2007-10-21 18:20:26.331
2007-10-21 23:26:02.604
2007-10-21 18:20:26.331
2007-10-21 23:26:02.604
[[490312.12371996 -72542.35275906 -65818.1989803 ]
 [485899.30473998 -71889.4706477  -65225.83509475]
 [481486.48621926 -71236.58859044 -64633.47123767]
 [477073.66815412 -70583.7065867  -64041.10740883]
 [472660.85054088 -69930.82463729 -63448.74360855]
 [468248.03337362 -69277.94273867 -62856.37983503]
 [463835.21664977 -68625.06089288 -62264.01608935]
 [459422.40036494 -67972.17909878 -61671.65237088]
 [455009.58451477 -67319.29735698 -61079.28867993]
 [450596.76909506 -66666.41566477 -60486.92501513]
 [446183.95410129 -66013.53402265 -59894.56137671]
 [441771.13952938 -65360.65242938 -59302.19776405]
 [437358.32537615 -64707.77088733 -58709.83417825]
 [432945.5116362  -64054.88939276 -58117.47061757]
 [428532.69830602 -63402.00794595 -57525.10708204]
 [424119.88538107 -62749.12654717 -56932.74357178]
 [419707.07285777 -62096.24519562 -56340.38008641]
 [415294.2607317  -61443.36389122 -55